import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const page=fs.readFileSync(path.join(root,'src','InstitutionalIntelligenceRefinedPage.tsx'),'utf8');
const css=fs.readFileSync(path.join(root,'src','institutional-intelligence-refined.css'),'utf8');
assert.match(page,/institutionalIntelligenceApi\.get/);
assert.match(page,/institutionalIntelligenceApi\.generate/);
assert.match(page,/institutionalIntelligenceApi\.history/);
assert.match(page,/Opportunity Inbox/);
assert.match(page,/Trade playbook/);
assert.match(page,/Invalidation/);
assert.match(page,/Snapshot history/);
assert.match(page,/positive_drivers/);
assert.match(page,/negative_drivers/);
assert.match(css,/grid-template-columns:minmax\(220px,260px\)/);
assert.match(css,/@media\(max-width:760px\)/);
console.log('UI Milestone 5 Institutional Intelligence assertions passed.');
