BEGIN;

ALTER TABLE option_contract_history
    ALTER COLUMN bid DROP NOT NULL,
    ALTER COLUMN ask DROP NOT NULL,
    ALTER COLUMN last DROP NOT NULL,
    ALTER COLUMN volume DROP NOT NULL,
    ALTER COLUMN open_interest DROP NOT NULL,
    ALTER COLUMN implied_volatility DROP NOT NULL,
    ALTER COLUMN delta DROP NOT NULL,
    ALTER COLUMN gamma DROP NOT NULL,
    ALTER COLUMN theta DROP NOT NULL,
    ALTER COLUMN vega DROP NOT NULL;

COMMIT;
