import type { Envelope, Health, Overview, Readiness, ScannerRun, ScannerResults, DailyScanRequest, DataRefreshRequest, ScannerUniverse, OpportunityRecord, OpportunityEvent, StageOpportunityRequest, OpportunityWorkflowState, IntelligenceBundle, TradePlan, ManagedPosition, PortfolioIntelligenceSnapshot, LearningReport, LearningPolicy, ExecutionIntent, ExecutionIntentAudit, DynamicExitInstruction } from './types';
const API_ROOT=(import.meta.env.VITE_API_ROOT||'/api/v1/platform').replace(/\/$/,'');
const SCANNER_ROOT=(import.meta.env.VITE_SCANNER_API_ROOT||'/api/v1/scanner').replace(/\/$/,'');
const INTELLIGENCE_ROOT=(import.meta.env.VITE_INTELLIGENCE_API_ROOT||'/api/v1/institutional-intelligence').replace(/\/$/,'');
const TRADE_BUILDER_ROOT=(import.meta.env.VITE_TRADE_BUILDER_API_ROOT||'/api/v1/trade-builder').replace(/\/$/,'');
const PORTFOLIO_INTELLIGENCE_ROOT=(import.meta.env.VITE_PORTFOLIO_INTELLIGENCE_API_ROOT||'/api/v1/portfolio-intelligence').replace(/\/$/,'');
const PORTFOLIO_RISK_ALLOCATION_ROOT=(import.meta.env.VITE_PORTFOLIO_RISK_ALLOCATION_API_ROOT||'/api/v1/portfolio-risk-allocation').replace(/\/$/,'');
const BROKER_PORTFOLIO_ROOT=(import.meta.env.VITE_BROKER_PORTFOLIO_API_ROOT||'/api/v1/broker-portfolio').replace(/\/$/,'');
const PERFORMANCE_LEARNING_ROOT=(import.meta.env.VITE_PERFORMANCE_LEARNING_API_ROOT||'/api/v1/performance-learning').replace(/\/$/,'');
const EXECUTION_WORKSPACE_ROOT=(import.meta.env.VITE_EXECUTION_WORKSPACE_API_ROOT||'/api/v1/execution-workspace').replace(/\/$/,'');
const DYNAMIC_POSITION_MANAGEMENT_ROOT=(import.meta.env.VITE_DYNAMIC_POSITION_MANAGEMENT_API_ROOT||'/api/v1/dynamic-position-management').replace(/\/$/,'');
const OPPORTUNITY_ROOT=(import.meta.env.VITE_OPPORTUNITY_API_ROOT||'/api/v1/opportunities').replace(/\/$/,'');
export class ApiError extends Error { constructor(public status:number,message:string,public payload?:unknown){super(message)} }
function headers(json=false){const h:Record<string,string>={'Accept':'application/json'};if(json)h['Content-Type']='application/json';const key=sessionStorage.getItem('trading-ai-api-key');if(key){h['X-API-Key']=key;h['X-Actor']='workstation-user'}return h;}
async function request<T>(url:string, init:RequestInit={}):Promise<Envelope<T>>{const r=await fetch(url,init);let body:unknown;try{body=await r.json()}catch{body={detail:r.statusText}}if(!r.ok)throw new ApiError(r.status,(body as any)?.detail||r.statusText,body);return body as Envelope<T>}
export async function apiGet<T>(path:string,signal?:AbortSignal):Promise<Envelope<T>>{return request<T>(`${API_ROOT}${path}`,{headers:headers(),signal})}
export const platformApi={health:(s?:AbortSignal)=>apiGet<Health>('/health',s),readiness:(s?:AbortSignal)=>apiGet<Readiness>('/readiness',s),overview:(s?:AbortSignal)=>apiGet<Overview>('/overview',s),portfolio:(s?:AbortSignal)=>apiGet<any>('/portfolio',s),risk:(s?:AbortSignal)=>apiGet<any>('/risk',s),execution:(s?:AbortSignal)=>apiGet<any>('/execution',s),positions:(s?:AbortSignal)=>apiGet<any>('/positions',s),exits:(s?:AbortSignal)=>apiGet<any>('/exit-instructions',s)};
export const scannerApi={
  universes:(s?:AbortSignal)=>request<ScannerUniverse[]>(`${SCANNER_ROOT}/universes`,{headers:headers(),signal:s}),
  runs:(s?:AbortSignal)=>request<ScannerRun[]>(`${SCANNER_ROOT}/runs`,{headers:headers(),signal:s}),
  run:(id:string,s?:AbortSignal)=>request<ScannerRun>(`${SCANNER_ROOT}/runs/${id}`,{headers:headers(),signal:s}),
  results:(id:string,s?:AbortSignal)=>request<ScannerResults>(`${SCANNER_ROOT}/runs/${id}/results`,{headers:headers(),signal:s}),
  refresh:(payload:DataRefreshRequest)=>request<ScannerRun>(`${SCANNER_ROOT}/data-refresh`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
  scan:(payload:DailyScanRequest)=>request<ScannerRun>(`${SCANNER_ROOT}/runs`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
};

export const opportunityApi={
  list:(state?:OpportunityWorkflowState,signal?:AbortSignal)=>request<OpportunityRecord[]>(`${OPPORTUNITY_ROOT}${state?`?state=${encodeURIComponent(state)}`:''}`,{headers:headers(),signal}),
  get:(id:string,signal?:AbortSignal)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}`,{headers:headers(),signal}),
  events:(id:string,signal?:AbortSignal)=>request<OpportunityEvent[]>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/events`,{headers:headers(),signal}),
  stage:(payload:StageOpportunityRequest)=>request<OpportunityRecord>(OPPORTUNITY_ROOT,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
  transition:(id:string,newState:OpportunityWorkflowState,expectedVersion:number,reason:string)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({new_state:newState,expected_version:expectedVersion,reason})}),
  designatePreferred:(id:string,expectedVersion:number,reason:string)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/preferred`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason})}),
};

export const institutionalIntelligenceApi={get:(id:string,signal?:AbortSignal)=>request<IntelligenceBundle>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}`,{headers:headers(),signal}),generate:(id:string)=>request<IntelligenceBundle>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}/generate`,{method:'POST',headers:headers(true)}),history:(id:string,signal?:AbortSignal)=>request<any[]>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}/history`,{headers:headers(),signal})};

export const tradeBuilderApi={list:(opportunityId?:string)=>request<TradePlan[]>(`${TRADE_BUILDER_ROOT}/plans${opportunityId?`?opportunity_id=${encodeURIComponent(opportunityId)}`:''}`,{headers:headers()}),build:(payload:Record<string,any>)=>request<TradePlan>(`${TRADE_BUILDER_ROOT}/plans`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),revalidate:(id:string)=>request<TradePlan>(`${TRADE_BUILDER_ROOT}/plans/${encodeURIComponent(id)}/revalidate`,{method:'POST',headers:headers(true),body:JSON.stringify({})}),transition:(id:string,expectedVersion:number,newState:string,reason:string)=>request<TradePlan>(`${TRADE_BUILDER_ROOT}/plans/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,new_state:newState,reason})})};


export const brokerPortfolioApi={
 synchronize:(portfolioId='PAPER-PRIMARY')=>request<any>(`${BROKER_PORTFOLIO_ROOT}/synchronize`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId,connect_broker:true})}),
 positions:(portfolioId='PAPER-PRIMARY')=>request<any[]>(`${BROKER_PORTFOLIO_ROOT}/positions?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),
 publication:(portfolioId='PAPER-PRIMARY')=>request<any>(`${BROKER_PORTFOLIO_ROOT}/publication?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),
 alerts:(portfolioId='PAPER-PRIMARY')=>request<any[]>(`${BROKER_PORTFOLIO_ROOT}/alerts?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),
};

export const portfolioIntelligenceApi={positions:(portfolioId='PAPER-PRIMARY')=>request<ManagedPosition[]>(`${PORTFOLIO_INTELLIGENCE_ROOT}/positions?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),snapshot:(portfolioId:string)=>request<PortfolioIntelligenceSnapshot|null>(`${PORTFOLIO_INTELLIGENCE_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/snapshot`,{headers:headers()}),generateSnapshot:(portfolioId:string,cash:number,buyingPower:number)=>request<PortfolioIntelligenceSnapshot>(`${PORTFOLIO_INTELLIGENCE_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/snapshots`,{method:'POST',headers:headers(true),body:JSON.stringify({cash,buying_power:buyingPower})}),action:(id:string,expectedVersion:number,action:string,reason:string,realizedPnl=0)=>request<ManagedPosition>(`${PORTFOLIO_INTELLIGENCE_ROOT}/positions/${encodeURIComponent(id)}/actions`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,action,reason,realized_pnl:realizedPnl})})};


export const dynamicPositionManagementApi={
 instructions:(positionId?:string,status?:string)=>{const q=new URLSearchParams();if(positionId)q.set('position_id',positionId);if(status)q.set('status',status);return request<DynamicExitInstruction[]>(`${DYNAMIC_POSITION_MANAGEMENT_ROOT}/instructions${q.toString()?`?${q}`:''}`,{headers:headers()})},
 setMode:(positionId:string,mode:string,reason:string)=>request<any>(`${DYNAMIC_POSITION_MANAGEMENT_ROOT}/positions/${encodeURIComponent(positionId)}/automation-mode`,{method:'POST',headers:headers(true),body:JSON.stringify({mode,reason})}),
 evaluate:(positionId:string,submitAutomatic=true)=>request<any>(`${DYNAMIC_POSITION_MANAGEMENT_ROOT}/positions/${encodeURIComponent(positionId)}/evaluate`,{method:'POST',headers:headers(true),body:JSON.stringify({submit_automatic:submitAutomatic})}),
 cycle:(portfolioId='PAPER-PRIMARY',submitAutomatic=true)=>request<any>(`${DYNAMIC_POSITION_MANAGEMENT_ROOT}/cycles`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId,submit_automatic:submitAutomatic})}),
 approve:(instructionId:string,reason:string,submit=false)=>request<any>(`${DYNAMIC_POSITION_MANAGEMENT_ROOT}/instructions/${encodeURIComponent(instructionId)}/approve`,{method:'POST',headers:headers(true),body:JSON.stringify({reason,submit})}),
};

export const performanceLearningApi={report:(portfolioId:string)=>request<LearningReport|null>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/report`,{headers:headers()}),generate:(portfolioId:string)=>request<LearningReport>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/reports`,{method:'POST',headers:headers(true)}),policies:()=>request<LearningPolicy[]>(`${PERFORMANCE_LEARNING_ROOT}/policies`,{headers:headers()}),propose:(payload:Record<string,any>)=>request<LearningPolicy>(`${PERFORMANCE_LEARNING_ROOT}/policies`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),transition:(id:string,targetState:string,reason:string)=>request<LearningPolicy>(`${PERFORMANCE_LEARNING_ROOT}/policies/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({target_state:targetState,reason})}),learningDashboard:(portfolioId:string)=>request<any>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/learning-dashboard`,{headers:headers()}),runLearningCycle:(portfolioId:string)=>request<any>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/learning-cycle`,{method:'POST',headers:headers(true)})};


export const executionWorkspaceApi={list:(state?:string,portfolioId='PAPER-PRIMARY')=>{const q=new URLSearchParams();if(state)q.set('state',state);if(portfolioId)q.set('portfolio_id',portfolioId);return request<ExecutionIntent[]>(`${EXECUTION_WORKSPACE_ROOT}/intents${q.toString()?`?${q}`:''}`,{headers:headers()})},compatibilityList:()=>request<ExecutionIntent[]>(`${API_ROOT}/execution`,{headers:headers()}),create:(tradePlanId:string,portfolioId?:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/from-trade-plan/${encodeURIComponent(tradePlanId)}`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId})}),transition:(id:string,expectedVersion:number,newState:string,reason:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,new_state:newState,reason})}),submit:(id:string,expectedVersion:number,reason:string,confirmation:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/submit`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason,confirmation})}),synchronize:(id:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/synchronize`,{method:'POST',headers:headers(true)}),cancel:(id:string,expectedVersion:number,reason:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/cancel`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason})}),reprice:(id:string,expectedVersion:number,reason:string,confirmation:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/reprice`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason,confirmation})}),retry:(id:string,expectedVersion:number,reason:string)=>request<ExecutionIntent>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/retry`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason})}),attempts:(tradePlanId:string,tradePlanVersion?:number)=>request<ExecutionIntent[]>(`${EXECUTION_WORKSPACE_ROOT}/trade-plans/${encodeURIComponent(tradePlanId)}/attempts${tradePlanVersion?`?trade_plan_version=${tradePlanVersion}`:''}`,{headers:headers()}),audit:(id:string)=>request<ExecutionIntentAudit[]>(`${EXECUTION_WORKSPACE_ROOT}/intents/${encodeURIComponent(id)}/audit`,{headers:headers()}),routingStatus:(portfolioId:string)=>request<any>(`${EXECUTION_WORKSPACE_ROOT}/routing-status/${encodeURIComponent(portfolioId)}`,{headers:headers()})};
export const stockIntelligenceApi={candidates:(params:Record<string,unknown>={})=>request<any>(`/api/v1/stock-intelligence/candidates?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)])).toString()}`,{headers:headers()}),candidate:(id:string)=>request<any>(`/api/v1/stock-intelligence/candidates/${encodeURIComponent(id)}`,{headers:headers()})};

const INSTITUTIONAL_OPTIONS_ROOT=(import.meta.env.VITE_INSTITUTIONAL_OPTIONS_API_ROOT||'/api/v1/institutional-options').replace(/\/$/,'');
export const institutionalOptionsApi={
  tradeBuilderConfig:()=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/handoff/trade-builder-config`,{headers:headers()}),
  workspaceList:(params:Record<string,unknown>={},signal?:AbortSignal)=>request<any[]>(`${INSTITUTIONAL_OPTIONS_ROOT}/workspace/opportunities?${new URLSearchParams(Object.entries(params).filter(([,v])=>v!==''&&v!=null).map(([k,v])=>[k,String(v)])).toString()}`,{headers:headers(),signal}),
  workspace:(id:string,signal?:AbortSignal)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/workspace/opportunities/${encodeURIComponent(id)}`,{headers:headers(),signal}),
  ingest:(publicationName='current_stock_intelligence')=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/opportunities/ingest?publication_name=${encodeURIComponent(publicationName)}`,{method:'POST',headers:headers(true)}),
  generateStrategies:(id:string)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/strategies/generate?opportunity_ids=${encodeURIComponent(id)}`,{method:'POST',headers:headers(true)}),
  optimizeContracts:(id:string)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/contracts/optimize?opportunity_ids=${encodeURIComponent(id)}`,{method:'POST',headers:headers(true)}),
  valueStrategies:(id:string)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/strategies/value?opportunity_ids=${encodeURIComponent(id)}`,{method:'POST',headers:headers(true)}),
  generateManagement:(id:string)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/management/generate?opportunity_ids=${encodeURIComponent(id)}`,{method:'POST',headers:headers(true)}),
  buildDecision:(id:string)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/decisions/build?opportunity_ids=${encodeURIComponent(id)}`,{method:'POST',headers:headers(true)}),
  handoffTradeBuilder:(id:string,payload:Record<string,unknown>)=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/opportunities/${encodeURIComponent(id)}/handoff/trade-builder`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
  handoffExecutionIntent:(handoffId:string,payload:Record<string,unknown>={})=>request<any>(`${INSTITUTIONAL_OPTIONS_ROOT}/handoffs/${encodeURIComponent(handoffId)}/execution-intent`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
};

export const portfolioRiskAllocationApi={current:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/current?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),build:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/build`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId})}),stress:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/stress`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId})}),fit:(candidate:any,portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/fit`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId,candidate})}),optimizerCurrent:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/optimizer/current?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),optimizerBuild:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/optimizer/build`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId,rebuild_decisions:true})}),recommendations:(portfolioId='PAPER-PRIMARY')=>request<any[]>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/optimizer/recommendations?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),continuousRun:(portfolioId='PAPER-PRIMARY')=>request<any>(`${PORTFOLIO_RISK_ALLOCATION_ROOT}/continuous-intelligence/run`,{method:'POST',headers:headers(true),body:JSON.stringify({portfolio_id:portfolioId})})};

const ANALYTICS_DASHBOARD_ROOT=(import.meta.env.VITE_ANALYTICS_DASHBOARD_API_ROOT||'/api/v1/analytics-dashboard').replace(/\/$/,'');
export const analyticsDashboardApi={
  inflection:(limit=1000,signal?:AbortSignal)=>request<any>(`${ANALYTICS_DASHBOARD_ROOT}/inflection?limit=${limit}`,{headers:headers(),signal}),
  optionsMispricing:(limit=3000,signal?:AbortSignal)=>request<any>(`${ANALYTICS_DASHBOARD_ROOT}/options-mispricing?limit=${limit}`,{headers:headers(),signal}),
};

const EXECUTION_INTELLIGENCE_ROOT=(import.meta.env.VITE_EXECUTION_INTELLIGENCE_API_ROOT||'/api/v1/execution-intelligence').replace(/\/$/,'');
export const executionIntelligenceApi={policy:()=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/policy`,{headers:headers()}),preflight:(id:string,reason='Manual execution preflight')=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/intents/${encodeURIComponent(id)}/preflight`,{method:'POST',headers:headers(true),body:JSON.stringify({reason})}),latest:(id:string)=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/intents/${encodeURIComponent(id)}/latest`,{headers:headers()}),dashboard:()=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/dashboard`,{headers:headers()}),workingAssessment:(id:string,reason='Manual working-order assessment')=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/intents/${encodeURIComponent(id)}/working-assessment`,{method:'POST',headers:headers(true),body:JSON.stringify({reason})}),workingTelemetry:(id:string)=>request<any>(`${EXECUTION_INTELLIGENCE_ROOT}/intents/${encodeURIComponent(id)}/working-telemetry`,{headers:headers()})};

const OPEX_INTELLIGENCE_ROOT=(import.meta.env.VITE_OPEX_INTELLIGENCE_API_ROOT||'/api/v1/opex-intelligence').replace(/\/$/,'');
export const opexIntelligenceApi={dashboard:(symbol?:string,signal?:AbortSignal)=>request<any>(`${OPEX_INTELLIGENCE_ROOT}/dashboard${symbol?`?symbol=${encodeURIComponent(symbol)}`:''}`,{headers:headers(),signal}),refresh:(cycles=3)=>request<any>(`${OPEX_INTELLIGENCE_ROOT}/refresh?cycles=${cycles}`,{method:'POST',headers:headers(true)}),realize:()=>request<any>(`${OPEX_INTELLIGENCE_ROOT}/realize-outcomes`,{method:'POST',headers:headers(true)})};
