import { useEffect, useMemo, useState } from 'react';
import { executionWorkspaceApi, executionIntelligenceApi } from './api';
import type { ExecutionIntent, ExecutionIntentAudit } from './types';
import './execution-workspace.css';

const money=(v:unknown)=>Number(v||0).toLocaleString(undefined,{style:'currency',currency:'USD'});
const fmt=(v:unknown)=>String(v??'—').replaceAll('_',' ');
const activeStates=new Set(['PAPER_READY','VALIDATED','APPROVED','SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED','CANCEL_REQUESTED']);

export function ExecutionWorkspacePage(){
 const [items,setItems]=useState<ExecutionIntent[]>([]);const [executionGate,setExecutionGate]=useState<any>(null);const [workingAssessment,setWorkingAssessment]=useState<any>(null);const [selectedId,setSelectedId]=useState('');const [audit,setAudit]=useState<ExecutionIntentAudit[]>([]);const [routing,setRouting]=useState<any>(null);const [query,setQuery]=useState('');const [state,setState]=useState('ACTIVE');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 const selected=items.find(x=>x.execution_intent_id===selectedId)||items[0]||null;
 const load=async()=>{setBusy(true);setMessage('');try{let rows:ExecutionIntent[]=[];try{const r=await executionWorkspaceApi.list(undefined,'PAPER-PRIMARY');rows=r.data||[]}catch(primary:any){try{const fallback=await executionWorkspaceApi.compatibilityList();rows=fallback.data||[];setMessage(`Canonical OMS endpoint failed (${primary?.status??'unknown'}): ${primary?.message||primary}. Loaded through the compatibility route.`)}catch(secondary:any){throw new Error(`Unable to load OMS queue. /api/v1/execution-workspace/intents: ${primary?.status??'error'} ${primary?.message||primary}; /api/v1/platform/execution: ${secondary?.status??'error'} ${secondary?.message||secondary}`)}}setItems(rows);setSelectedId(id=>rows.some(x=>x.execution_intent_id===id)?id:(rows[0]?.execution_intent_id||''));}catch(e:any){setItems([]);setSelectedId('');setMessage(e.message||String(e))}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!selected)return;executionWorkspaceApi.audit(selected.execution_intent_id).then(r=>setAudit(r.data||[])).catch(()=>setAudit([]));executionWorkspaceApi.routingStatus(selected.portfolio_id).then(r=>setRouting(r.data)).catch(()=>setRouting(null));},[selected?.execution_intent_id]);
 const filtered=useMemo(()=>items.filter(x=>{const q=query.trim().toUpperCase();const match=!q||`${x.symbol} ${x.strategy} ${x.execution_intent_id}`.toUpperCase().includes(q);const sm=state==='ALL'||(state==='ACTIVE'?activeStates.has(x.state):x.state===state);return match&&sm}),[items,query,state]);
 const counts=useMemo(()=>({pending:items.filter(x=>['PAPER_READY','VALIDATED','APPROVED'].includes(x.state)).length,submitted:items.filter(x=>['SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED','CANCEL_REQUESTED'].includes(x.state)).length,filled:items.filter(x=>x.state==='FILLED').length,rejected:items.filter(x=>x.state==='REJECTED').length}),[items]);
 async function mutate(action:()=>Promise<any>){setBusy(true);setMessage('');try{await action();await load()}catch(e:any){setMessage(e.message||String(e))}finally{setBusy(false)}}
 function reason(label:string){return prompt(`Reason for ${label}`)?.trim()||''}
 function transition(target:string){if(!selected)return;const why=reason(target);if(!why)return;mutate(()=>executionWorkspaceApi.transition(selected.execution_intent_id,selected.version,target,why))}
 function preflight(){if(!selected)return;mutate(async()=>{const r=await executionIntelligenceApi.preflight(selected.execution_intent_id,'Manual pre-route execution validation');setExecutionGate(r.data);return r})}
 function submit(){if(!selected)return;const why=reason('paper submission');if(!why)return;const expected=`SUBMIT PAPER INTENT ${selected.execution_intent_id}`;const confirmation=prompt(`Type exactly:\n${expected}`)||'';if(!confirmation)return;mutate(()=>executionWorkspaceApi.submit(selected.execution_intent_id,selected.version,why,confirmation))}
 function cancel(){if(!selected)return;const why=reason('cancel');if(!why)return;mutate(()=>executionWorkspaceApi.cancel(selected.execution_intent_id,selected.version,why))}
 async function assessWorking(){if(!selected)return;setBusy(true);setMessage('');try{const r=await executionIntelligenceApi.workingAssessment(selected.execution_intent_id);setWorkingAssessment(r.data)}catch(e:any){setMessage(e.message||String(e))}finally{setBusy(false)}}
 function repriceWorking(){if(!selected||workingAssessment?.recommended_action!=='REPRICE')return;const why=reason('governed reprice');if(!why)return;const expected=`REPRICE PAPER INTENT ${selected.execution_intent_id}`;const confirmation=prompt(`Type exactly:\n${expected}`)||'';if(!confirmation)return;mutate(()=>executionWorkspaceApi.reprice(selected.execution_intent_id,selected.version,why,confirmation))}
 return <section className="execution-workspace">
  <header className="ew-header"><div><span>Institutional OMS</span><h2>Execution Workspace</h2><p>Review, validate, submit, and monitor governed IBKR paper intents.</p></div><button onClick={load} disabled={busy}>{busy?'Refreshing…':'Refresh queue'}</button></header>
  <div className="ew-kpis"><article><b>{counts.pending}</b><span>Pending review</span></article><article><b>{counts.submitted}</b><span>Open broker orders</span></article><article><b>{counts.filled}</b><span>Filled</span></article><article><b>{counts.rejected}</b><span>Rejected</span></article><article><b>{routing?.status||'Not reported'}</b><span>Paper routing</span></article></div>
  {message&&<div className="ew-message">{message}</div>}
  <div className="ew-layout">
   <aside className="ew-queue"><div className="ew-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search symbol or intent"/><select value={state} onChange={e=>setState(e.target.value)}><option value="ACTIVE">Active</option><option value="ALL">All</option><option value="PAPER_READY">Paper ready</option><option value="VALIDATED">Validated</option><option value="APPROVED">Approved</option><option value="SUBMITTED">Submitted</option><option value="FILLED">Filled</option><option value="CANCELLED">Cancelled</option><option value="REJECTED">Rejected</option></select></div>
    <div className="ew-list">{filtered.map(x=><button key={x.execution_intent_id} className={selected?.execution_intent_id===x.execution_intent_id?'active':''} onClick={()=>setSelectedId(x.execution_intent_id)}><div><strong>{x.symbol}</strong><span>{fmt(x.strategy)}</span></div><em>{fmt(x.state)}</em><small>{money(x.validation.max_loss)} max risk · v{x.version}</small></button>)}{!filtered.length&&<p>No execution intents match this view.</p>}</div>
   </aside>
   <main className="ew-review">{selected?<>
    <div className="ew-title"><div><span>{selected.execution_intent_id}</span><h3>{selected.symbol} · {fmt(selected.strategy)}</h3><p>Trade plan {selected.trade_plan_id} · Opportunity {selected.opportunity_id}</p></div><strong className={`state ${selected.state.toLowerCase()}`}>{fmt(selected.state)}</strong></div>
    <div className="ew-grid"><article><span>Maximum loss</span><b>{money(selected.validation.max_loss)}</b></article><article><span>Estimated notional</span><b>{money(selected.validation.estimated_notional)}</b></article><article><span>Buying power</span><b>{selected.validation.buying_power==null?'Not reported':money(selected.validation.buying_power)}</b></article><article><span>Paper account</span><b>{selected.account_id}</b></article></div>
    <section className="ew-card"><h4>Pre-trade validation</h4><div className="ew-checks">{Object.entries(selected.validation.checks||{}).map(([k,v])=><div key={k} className={v?'pass':'fail'}><b>{v?'✓':'!'}</b><span>{fmt(k)}</span></div>)}</div>{selected.validation.warnings?.map((w,i)=><p className="warning" key={i}>{w}</p>)}</section>
    <section className="ew-card"><h4>Portfolio impact & allocation</h4>{(()=>{const pd:any=selected.metadata?.portfolio_decision||{};const impact:any=pd.portfolio_impact||{};const alloc:any=pd.capital_allocation||{};const scores:any=pd.scores||{};return Object.keys(pd).length?<><div className="ew-management-grid"><div><span>Portfolio fit</span><b>{Number(scores.portfolio_fit_score||0).toFixed(1)}</b></div><div><span>Final portfolio score</span><b>{Number(scores.final_portfolio_score||0).toFixed(1)}</b></div><div><span>Recommended quantity</span><b>{alloc.recommended_quantity??'—'}</b></div><div><span>Recommended capital</span><b>{money(alloc.recommended_capital)}</b></div><div><span>Marginal VaR</span><b>{money(impact.marginal_var_95)}</b></div><div><span>Marginal heat</span><b>{Number(impact.marginal_heat_pct||0).toFixed(2)}%</b></div><div><span>Heat before</span><b>{Number(impact.before?.portfolio_heat_pct||0).toFixed(2)}%</b></div><div><span>Heat after</span><b>{Number(impact.after?.portfolio_heat_pct||0).toFixed(2)}%</b></div><div><span>Portfolio decision</span><b>{fmt(pd.decision)}</b></div></div><p className="ew-management-note">{(pd.explainability?.positive_reasons||[]).join(' · ')||pd.explainability?.summary||'Portfolio-aware decision is attached.'}</p></>:<p className="warning">No portfolio-aware decision is attached. Rebuild Decision Intelligence before creating the trade plan.</p>})()}</section>
    <section className="ew-card"><h4>Dynamic management & exit plan</h4>{(()=>{const dm:any=selected.metadata?.dynamic_management||{};const targets:any[]=dm.underlying_targets||[];return Object.keys(dm).length?<><div className="ew-management-grid"><div><span>Entry zone</span><b>{dm.underlying_entry_zone_low==null?'—':`${money(dm.underlying_entry_zone_low)} – ${money(dm.underlying_entry_zone_high)}`}</b></div><div><span>Structural stop</span><b>{dm.underlying_stop==null?'—':money(dm.underlying_stop)}</b></div><div><span>Trailing policy</span><b>{fmt(dm.trailing_policy)}</b></div><div><span>Emergency option stop</span><b>{dm.emergency_option_stop_pct==null?'—':`${Number(dm.emergency_option_stop_pct)*100}% loss`}</b></div><div><span>Theta exit</span><b>{dm.theta_exit_days_to_expiry==null?'—':`${dm.theta_exit_days_to_expiry} DTE`}</b></div><div><span>Partial-profit fraction</span><b>{dm.partial_profit_fraction==null?'—':`${Math.round(Number(dm.partial_profit_fraction)*100)}%`}</b></div><div><span>Volatility exit</span><b>{fmt(dm.volatility_exit_rule)}</b></div><div><span>Assignment rule</span><b>{fmt(dm.assignment_risk_rule)}</b></div><div><span>Management mode</span><b>{fmt(selected.metadata?.management_activation==='ACTIVE'?'ACTIVE PLATFORM MANAGEMENT':dm.management_mode||'PLATFORM MANAGED AFTER FILL')}</b></div></div><div className="ew-targets">{targets.slice(0,3).map((t:any,i:number)=><article key={i}><span>Target {i+1}</span><b>{money(t)}</b></article>)}</div>{(dm.invalidation_reasons||[]).length>0&&<div className="ew-rules"><span>Invalidation rules</span><ul>{dm.invalidation_reasons.map((x:string,i:number)=><li key={i}>{fmt(x)}</li>)}</ul></div>}<p className="ew-management-note">Entry submission sends the selected option order. Dynamic exits are armed after a confirmed fill and monitored by the platform; broker-native protection is not submitted until explicitly supported by the exit policy.</p></>:<p className="warning">No dynamic management plan is attached. Return to Institutional Options and recreate the trade plan from the selected decision snapshot.</p>})()}</section>
    <section className="ew-card"><h4>Order legs</h4><div className="ew-legs">{selected.legs.map((l:any,i)=><article key={i}><b>{l.side} {l.quantity} {l.option_right}</b><span>{l.option_symbol||selected.symbol}</span><span>{l.expiry} · {l.strike}</span><strong>@ {money(l.limit_price)}</strong></article>)}</div></section>
    <section className="ew-card"><h4>Execution intelligence</h4>{executionGate&&executionGate.execution_intent_id===selected.execution_intent_id?<><div className="ew-management-grid"><div><span>Decision</span><b>{fmt(executionGate.decision)}</b></div><div><span>Confidence</span><b>{Number(executionGate.execution_confidence||0).toFixed(1)}%</b></div><div><span>Approved reference</span><b>{money(executionGate.approved_reference_price)}</b></div><div><span>Fresh executable</span><b>{money(executionGate.fresh_executable_price)}</b></div><div><span>Adverse drift</span><b>{Number(executionGate.adverse_price_drift_pct||0).toFixed(2)}%</b></div><div><span>Quote age</span><b>{Number(executionGate.quote_age_seconds||0).toFixed(2)}s</b></div><div><span>Fresh max loss</span><b>{money(executionGate.fresh_max_loss)}</b></div><div><span>Risk budget</span><b>{money(executionGate.risk_budget_amount)}</b></div></div><div className="ew-checks">{Object.entries(executionGate.validation_json?.checks||{}).map(([k,v])=><div key={k} className={v?'pass':'fail'}><b>{v?'✓':'!'}</b><span>{fmt(k)}</span></div>)}</div></>:<p>Run a direct Polygon preflight immediately before paper routing.</p>}</section>
    <section className="ew-card"><h4>Working-order intelligence</h4>{workingAssessment&&workingAssessment.execution_intent_id===selected.execution_intent_id?<div className="ew-management-grid"><div><span>Recommended action</span><b>{fmt(workingAssessment.recommended_action)}</b></div><div><span>Current limit</span><b>{money(workingAssessment.current_limit_price)}</b></div><div><span>Governed limit</span><b>{money(workingAssessment.governed_limit_price)}</b></div><div><span>Working age</span><b>{Number(workingAssessment.working_age_seconds||0).toFixed(1)}s</b></div><div><span>Filled</span><b>{workingAssessment.filled_quantity}</b></div><div><span>Remaining</span><b>{workingAssessment.remaining_quantity}</b></div></div>:<p>Assess a working order against fresh Polygon quotes and the approved execution envelope.</p>}</section><section className="ew-card"><h4>Broker status</h4><div className="ew-broker"><span>Environment</span><b>PAPER</b><span>Live trading</span><b>Disabled</b><span>Routing</span><b>{routing?.status||'Not reported'}</b><span>Broker order</span><b>{selected.broker?.submission?.broker_order_id??'Not submitted'}</b><span>Filled</span><b>{selected.broker?.order_status?.filled_quantity??0}</b></div></section>
    <div className="ew-actions">{selected.state==='PAPER_READY'&&<button onClick={()=>transition('VALIDATED')}>Validate</button>}{selected.state==='VALIDATED'&&<button onClick={()=>transition('APPROVED')}>Approve</button>}{selected.state==='APPROVED'&&<button onClick={preflight}>Run live Polygon preflight</button>}{selected.state==='APPROVED'&&<button className="primary" onClick={submit}>Submit atomic IBKR paper order</button>}{['SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED','CANCEL_REQUESTED'].includes(selected.state)&&<button onClick={()=>mutate(()=>executionWorkspaceApi.synchronize(selected.execution_intent_id))}>Refresh broker status</button>}{['SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED'].includes(selected.state)&&<button onClick={assessWorking}>Assess working order</button>}{['SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED'].includes(selected.state)&&workingAssessment?.execution_intent_id===selected.execution_intent_id&&workingAssessment?.recommended_action==='REPRICE'&&<button onClick={repriceWorking}>Apply governed reprice</button>}{['SUBMITTED','ACKNOWLEDGED','PARTIALLY_FILLED'].includes(selected.state)&&<button className="danger" onClick={cancel}>Cancel order</button>}{['PAPER_READY','VALIDATED','APPROVED'].includes(selected.state)&&<button className="danger" onClick={()=>transition('REJECTED')}>Reject</button>}<button onClick={()=>location.hash='#/trade-builder'}>Edit trade plan</button><button onClick={()=>location.hash='#/portfolio'}>Open portfolio</button></div>
   </>:<div className="ew-empty">Prepare a paper intent in Trade Builder to populate this queue.</div>}</main>
   <aside className="ew-timeline"><h3>Execution timeline</h3>{audit.map(x=><article key={x.event_id}><i/><div><b>{fmt(x.event_type)}</b><span>{x.previous_state?`${fmt(x.previous_state)} → `:''}{fmt(x.new_state)}</span><p>{x.reason}</p><small>{new Date(x.event_timestamp).toLocaleString()} · {x.actor}</small></div></article>)}{!audit.length&&<p>No audit events.</p>}</aside>
  </div>
 </section>
}
