import {useEffect,useMemo,useState} from 'react';
import {executionIntelligenceApi} from './api';
const money=(v:any)=>Number(v||0).toLocaleString(undefined,{style:'currency',currency:'USD'});const fmt=(v:any)=>String(v??'—').replaceAll('_',' ');
export function ExecutionIntelligencePage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [filter,setFilter]=useState('ALL');
 const load=()=>executionIntelligenceApi.dashboard().then(r=>{setData(r.data);setError('')}).catch(e=>setError(e.message||String(e)));
 useEffect(()=>{void load()},[]);const orders:any[]=data?.orders||[];const rows=useMemo(()=>filter==='ALL'?orders:orders.filter(x=>String(x.state).toUpperCase()===filter),[orders,filter]);
 const states=Array.from(new Set(orders.map(x=>String(x.state).toUpperCase()))).sort();
 return <section className="production-operations-page"><div className="page-title"><div><h2>Execution Intelligence</h2><p>Live Polygon repricing, smart limits, IBKR lifecycle telemetry, fill quality and governed working-order intelligence.</p></div><button onClick={load}>Refresh</button></div>{error&&<p className="provider-warning">{error}</p>}
 <div className="ops-readiness-grid"><article><span>Preflights</span><strong>{data?.count??0}</strong></article><article><span>Execute</span><strong>{data?.execute??0}</strong></article><article><span>Fill rate</span><strong>{Number(data?.fill_rate_pct||0).toFixed(1)}%</strong></article><article><span>Avg quality</span><strong>{Number(data?.average_execution_quality||0).toFixed(1)}</strong></article><article><span>Avg slippage</span><strong>{Number(data?.average_realized_slippage_pct||0).toFixed(2)}%</strong></article><article><span>Avg quote age</span><strong>{Number(data?.average_quote_age_seconds||0).toFixed(1)}s</strong></article></div>
 <div style={{display:'flex',gap:8,margin:'12px 0',flexWrap:'wrap'}}><button onClick={()=>setFilter('ALL')} className={filter==='ALL'?'active':''}>All {orders.length}</button>{states.map(s=><button key={s} onClick={()=>setFilter(s)} className={filter===s?'active':''}>{fmt(s)} {orders.filter(x=>String(x.state).toUpperCase()===s).length}</button>)}</div>
 <div className="table-wrap"><table><thead><tr><th>Updated</th><th>Symbol</th><th>Strategy</th><th>State</th><th>Confidence</th><th>Approved</th><th>Mid</th><th>Submitted</th><th>Fill</th><th>Slippage</th><th>Fill %</th><th>Quality</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.execution_intent_id}><td>{new Date(x.updated_at).toLocaleString()}</td><td><b>{x.symbol}</b></td><td>{fmt(x.strategy)}</td><td>{fmt(x.state)}</td><td>{Number(x.execution_confidence||0).toFixed(1)}%</td><td>{money(x.approved_reference_price)}</td><td>{money(x.fresh_midpoint_price)}</td><td>{money(x.submitted_limit_price)}</td><td>{x.average_fill_price==null?'—':money(x.average_fill_price)}</td><td>{x.realized_slippage_pct==null?'—':`${Number(x.realized_slippage_pct).toFixed(2)}%`}</td><td>{Number(x.fill_rate_pct||0).toFixed(1)}%</td><td>{Number(x.execution_quality_score||0).toFixed(1)}</td></tr>)}</tbody></table></div>
 <h3 style={{marginTop:24}}>Recent preflight decisions</h3><div className="table-wrap"><table><thead><tr><th>Time</th><th>Symbol</th><th>Strategy</th><th>Decision</th><th>Confidence</th><th>Reference</th><th>Fresh executable</th><th>Market drift</th><th>Quote age</th><th>Limit</th></tr></thead><tbody>{(data?.snapshots||[]).slice(0,100).map((x:any)=><tr key={x.execution_snapshot_id}><td>{new Date(x.created_at).toLocaleString()}</td><td><b>{x.symbol}</b></td><td>{fmt(x.strategy)}</td><td>{fmt(x.decision)}</td><td>{Number(x.execution_confidence).toFixed(1)}%</td><td>{money(x.approved_reference_price)}</td><td>{money(x.fresh_executable_price)}</td><td>{Number(x.adverse_price_drift_pct).toFixed(2)}%</td><td>{x.quote_age_seconds==null?'—':`${Number(x.quote_age_seconds).toFixed(1)}s`}</td><td>{money(x.governed_limit_price)}</td></tr>)}</tbody></table></div></section>}
