import { useEffect, useMemo, useState } from 'react';
import { analyticsDashboardApi } from './api';
import { AnalyticsMetric, AnalyticsTable, DetailDrawer, DistributionBars, Histogram, fmt } from './AnalyticsShared';

type ScoreBand={label:string;minimum:number;maximum:number}|null;
const toggle=(current:string|null,next:string)=>current===next?null:next;

export function InflectionAnalyticsPage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<any>(null);const [query,setQuery]=useState('');
 const [transition,setTransition]=useState<string|null>(null);const [sector,setSector]=useState<string|null>(null);const [strategy,setStrategy]=useState<string|null>(null);const [regime,setRegime]=useState<string|null>(null);const [scoreBand,setScoreBand]=useState<ScoreBand>(null);const [sortComponent,setSortComponent]=useState<string|null>(null);
 useEffect(()=>{
  const controller=new AbortController();setError('');
  analyticsDashboardApi.inflection(5000,controller.signal).then(response=>{if(!controller.signal.aborted){setData(response.data);setError('')}}).catch(reason=>{if(controller.signal.aborted||(reason instanceof DOMException&&reason.name==='AbortError'))return;setError(reason instanceof Error?reason.message:String(reason))});
  return()=>controller.abort();
 },[]);
 const candidates=data?.candidates??[];
 const filtered=useMemo(()=>{
   const rows=candidates.filter((row:any)=>(!query||row.symbol.toLowerCase().includes(query.toLowerCase())||String(row.company_name??'').toLowerCase().includes(query.toLowerCase()))&&(!transition||row.transition_state===transition)&&(!sector||row.sector===sector)&&(!strategy||row.strategy===strategy)&&(!regime||row.market_regime===regime)&&(!scoreBand||(Number(row.score)>=scoreBand.minimum&&Number(row.score)<scoreBand.maximum)||(scoreBand?.maximum===100&&Number(row.score)===100)));
   if(!sortComponent)return rows;
   return [...rows].sort((a,b)=>Number(b.components?.[sortComponent]??-Infinity)-Number(a.components?.[sortComponent]??-Infinity));
 },[candidates,query,transition,sector,strategy,regime,scoreBand,sortComponent]);
 const clear=()=>{setTransition(null);setSector(null);setStrategy(null);setRegime(null);setScoreBand(null);setSortComponent(null)};
 const active=[scoreBand&&`Score ${scoreBand.label}`,transition&&`Transition ${transition}`,sector&&`Sector ${sector}`,strategy&&`Strategy ${strategy}`,regime&&`Regime ${regime}`,sortComponent&&`Sorted by ${sortComponent}`].filter(Boolean) as string[];
 if(error)return <section className="analytics-page"><p className="provider-warning">{error}</p></section>;
 if(!data)return <section className="analytics-page"><p>Loading governed inflection analytics…</p></section>;
 const summary=data.summary??{};
 return <section className="analytics-page"><div className="analytics-page-title"><div><span className="eyebrow">Analytics</span><h2>Inflection Analytics</h2><p>Universe-wide distribution, transition state, component contribution, and threshold proximity from the latest governed publication.</p></div><div className="publication-chip"><span>{summary.status}</span><strong>{summary.source_run_id}</strong><small>{summary.published_at}</small></div></div>
 <div className="analytics-metric-grid"><AnalyticsMetric label="Symbols analyzed" value={fmt(summary.symbols_analyzed,0)}/><AnalyticsMetric label="Average score" value={fmt(summary.average_score,2)}/><AnalyticsMetric label="Median score" value={fmt(summary.median_score,2)}/><AnalyticsMetric label="High conviction" value={fmt(summary.high_conviction,0)}/><AnalyticsMetric label="Actionable" value={fmt(summary.actionable,0)}/><AnalyticsMetric label="Watch" value={fmt(summary.watch,0)}/></div>
 <div className="analytics-grid analytics-grid-wide"><Histogram title="Score histogram" rows={data.histogram??[]} markers={[{label:'Watch',value:60},{label:'Actionable',value:70},{label:'High conviction',value:80}]} selected={scoreBand?.label??null} onSelect={(row:any)=>setScoreBand(scoreBand?.label===row.label?null:{label:String(row.label),minimum:Number(row.minimum),maximum:Number(row.maximum)})}/><section className="analytics-panel"><header><h3>Percentile bands</h3></header><div className="percentile-grid">{Object.entries(data.percentiles??{}).map(([name,value])=><div key={name}><span>{name.toUpperCase()}</span><strong>{fmt(value,2)}</strong></div>)}</div><h4>Near high-conviction threshold</h4><div className="threshold-list">{(data.near_threshold??[]).map((row:any)=><div key={row.name} role="button" tabIndex={0} onClick={()=>setScoreBand({label:row.name,minimum:Number(row.minimum),maximum:Number(row.maximum)})}><span>{row.name}</span><strong>{row.count}</strong></div>)}</div></section></div>
 <div className="analytics-grid"><DistributionBars title="Transition state" rows={data.by_transition_state??[]} selected={transition} onSelect={(row:any)=>setTransition(toggle(transition,String(row.name)))}/><DistributionBars title="Sector" rows={data.by_sector??[]} selected={sector} onSelect={(row:any)=>setSector(toggle(sector,String(row.name)))}/><DistributionBars title="Strategy" rows={data.by_strategy??[]} selected={strategy} onSelect={(row:any)=>setStrategy(toggle(strategy,String(row.name)))}/><DistributionBars title="Market regime" rows={data.by_market_regime??[]} selected={regime} onSelect={(row:any)=>setRegime(toggle(regime,String(row.name)))}/><DistributionBars title="Component score averages" rows={data.component_averages??[]} valueLabel="average" selected={sortComponent} onSelect={(row:any)=>setSortComponent(toggle(sortComponent,String(row.name)))}/></div>
 <section className="analytics-panel"><header className="table-header"><div><h3>Candidate explorer</h3><p>{filtered.length} governed candidates</p></div><div className="analytics-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search symbol or company"/></div></header>{active.length>0&&<div className="analytics-active-filters">{active.map(label=><span className="analytics-filter-chip" key={label}>{label}</span>)}<button className="analytics-clear-filters" onClick={clear}>Clear chart filters</button></div>}<AnalyticsTable rows={filtered.slice(0,1000)} onSelect={setSelected} columns={[{key:'symbol',label:'Symbol'},{key:'company_name',label:'Company'},{key:'score',label:'Score',render:r=><strong>{fmt(r.score,2)}</strong>},{key:'confidence',label:'Confidence',render:r=>fmt(r.confidence,1)},{key:'transition_state',label:'Transition'},{key:'direction',label:'Direction'},{key:'sector',label:'Sector'},{key:'strategy',label:'Strategy'},{key:'market_regime',label:'Regime'},{key:'conviction',label:'Conviction'},{key:'opportunity_state',label:'Opportunity state'},{key:'primary_timeframe',label:'Primary TF'},{key:'threshold_gap',label:'Gap to 80',render:r=>fmt(r.threshold_gap,2)}]}/></section>
 {selected&&<DetailDrawer title={`${selected.symbol} inflection`} row={selected} onClose={()=>setSelected(null)}/>}</section>;
}
