import { useEffect, useMemo, useState } from 'react';
import { opexIntelligenceApi } from './api';

const n=(v:any,d=1)=>Number.isFinite(Number(v))?Number(v).toFixed(d):'—';
const money=(v:any)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
function Metric({label,value}:{label:string;value:any}){return <div className="opex-metric"><span>{label}</span><strong>{value}</strong></div>}
function Bar({label,value}:{label:string;value:number}){return <div className="opex-bar-row"><span>{label}</span><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div><b>{n(value)}%</b></div>}
function RangeRows({title,ranges}:{title:string;ranges:any}){return <section className="opex-card"><h3>{title}</h3>{['50','68','90'].map(k=><div className="opex-range" key={k}><b>{k}%</b><span>{money(ranges?.[k]?.low)} — {money(ranges?.[k]?.high)}</span></div>)}</section>}

export function OpexIntelligencePage(){
  const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [symbol,setSymbol]=useState('SPX');const [expiration,setExpiration]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const r=await opexIntelligenceApi.dashboard(symbol);setData(r.data)}catch(e:any){setError(e?.message||String(e))}finally{setLoading(false)}};
  useEffect(()=>{load()},[symbol]);
  const forecasts=useMemo(()=>data?.forecasts||[],[data]);
  useEffect(()=>{if(forecasts.length&&!forecasts.some((x:any)=>x.expiration===expiration))setExpiration(forecasts[0].expiration)},[forecasts,expiration]);
  const f=forecasts.find((x:any)=>x.expiration===expiration)||forecasts[0];const cross=(data?.cross_opex||[])[0];
  if(loading)return <div className="opex-page"><h2>OPEX intelligence</h2><p>Loading probabilistic path forecasts…</p></div>;
  return <div className="opex-page">
    <div className="page-title"><div><h2>OPEX Intelligence</h2><p>Settlement distribution, conditional path intelligence, dealer-flow forecasting and cross-expiration transitions for SPX, NDX and RUT.</p></div><button onClick={async()=>{await opexIntelligenceApi.refresh(3);await load()}}>Refresh forecast</button></div>
    {error&&<div className="opex-error">{error}</div>}
    <div className="opex-tabs">{['SPX','NDX','RUT'].map(x=><button className={symbol===x?'active':''} onClick={()=>setSymbol(x)} key={x}>{x}</button>)}</div>
    <div className="opex-cycle-tabs">{forecasts.map((x:any)=><button className={f?.expiration===x.expiration?'active':''} onClick={()=>setExpiration(x.expiration)} key={x.expiration}><b>{x.expiration}</b><span>{x.dte} DTE · {String(x.cycle_type).replaceAll('_',' ')}</span></button>)}</div>
    {!f?<div className="opex-empty">No OPEX forecast is published yet. Run options ingestion/finalization or click Refresh forecast.</div>:<>
      <section className="opex-summary"><h3>{symbol} · {f.expiration}</h3><p>{f.summary}</p><div className="opex-metrics"><Metric label="Spot" value={money(f.spot)}/><Metric label="Confidence" value={`${n(f.confidence?.overall)}%`}/><Metric label="Dealer pressure" value={n(f.dealer?.pressure_score)}/><Metric label="Dominant scenario" value={[...(f.scenarios||[])].sort((a:any,b:any)=>b.probability-a.probability)[0]?.name?.replaceAll('_',' ')||'—'}/></div></section>

      <section className="opex-actionable"><div><span>DOMINANT-SCENARIO ACTIONABLE RANGE</span><strong>{money(f.actionable_range?.low)} — {money(f.actionable_range?.high)}</strong><em>{String(f.actionable_range?.scenario||'').replaceAll('_',' ')} · {n(f.actionable_range?.scenario_probability)}%</em></div><p>{f.actionable_range?.definition}</p></section>

      <div className="opex-grid three">
        <RangeRows title="Unconditional settlement ranges" ranges={f.unconditional_ranges||f.ranges}/>
        <RangeRows title="Model-calibrated settlement ranges" ranges={f.model_calibrated_ranges||f.ranges}/>
        <section className="opex-card"><h3>Distribution evidence</h3><div className="opex-level-line"><span>Surface method</span><b>{f.surface_distribution?.status==='READY'?'Risk-neutral density':'Fallback'}</b></div><div className="opex-level-line"><span>Surface quality</span><b>{n(f.surface_distribution?.quality)}%</b></div><div className="opex-level-line"><span>Historical OPEX analogs</span><b>{f.historical_opex_analogs?.sample_size||0}</b></div><div className="opex-level-line"><span>Bayesian prior used</span><b>{f.posterior_update?.prior_used?'YES':'NO'}</b></div><div className="opex-level-line"><span>68% width change</span><b>{f.posterior_update?.width_change_pct==null?'—':`${n(f.posterior_update?.width_change_pct)}%`}</b></div></section>
      </div>

      <div className="opex-grid two">
        <section className="opex-card"><h3>Primary magnet & zone probability</h3><div className="opex-level-line"><span>Primary magnet</span><b>{money(f.magnet?.price)}</b></div><div className="opex-level-line"><span>Exact / narrow strike probability</span><b>{n(f.magnet?.probability)}%</b></div><div className="opex-level-line"><span>Magnet zone</span><b>{money(f.magnet?.zone?.low)} — {money(f.magnet?.zone?.high)}</b></div><div className="opex-level-line"><span>Magnet-zone probability</span><b>{n(f.magnet?.zone?.probability)}%</b></div><div className="opex-level-line"><span>Support / resistance</span><b>{money(f.levels?.support)} / {money(f.levels?.resistance)}</b></div></section>
        <section className="opex-card"><h3>Scenario posterior & evidence</h3>{(f.scenarios||[]).map((s:any)=><Bar key={s.name} label={String(s.name).replaceAll('_',' ')} value={s.probability}/>)}<div className="opex-evidence-net"><span>Net directional evidence</span><b>{n(f.scenario_evidence?.net_directional_score)}</b></div>{(f.scenario_evidence?.rows||[]).map((r:any)=><div className="opex-evidence-row" key={r.factor}><span>{String(r.factor).replaceAll('_',' ')}</span><b>{r.signed_score>0?'+':''}{n(r.signed_score)}</b><em>{r.direction} · weight {n(r.weight,2)}</em></div>)}</section>
      </div>

      <section className="opex-card"><h3>Event-conditioned distributions</h3><div className="opex-condition-grid">{(f.conditional_distributions||[]).map((x:any)=><div className="opex-condition" key={x.name}><strong>{String(x.name).replaceAll('_',' ')}</strong><b>{n(x.probability)}%</b><span>{money(x.range?.low)} — {money(x.range?.high)}</span><em>{x.condition}</em></div>)}</div></section>

      <section className="opex-card"><h3>Path probabilities to key levels</h3><div className="opex-table-wrap"><table><thead><tr><th>Level</th><th>Price</th><th>Side</th><th>Touch</th><th>Acceptance</th><th>First touch</th><th>Hold</th><th>Break</th></tr></thead><tbody>{(f.path_distribution?.levels||[]).map((r:any)=><tr key={`${r.label}-${r.price}`}><td>{String(r.label).replaceAll('_',' ')}</td><td>{money(r.price)}</td><td>{r.side}</td><td>{n(r.touch_probability)}%</td><td>{n(r.acceptance_probability)}%</td><td>{n(r.first_touch_probability)}%</td><td>{n(r.hold_probability)}%</td><td>{n(r.break_probability)}%</td></tr>)}</tbody></table></div></section>

      <div className="opex-grid two">
       <section className="opex-card"><h3>Level migration forecast</h3>{[['Gamma flip','gamma_flip'],['Call wall','call_wall'],['Put wall','put_wall']].map(([label,key])=>{const m=f.migration?.[key];return <div className="opex-migration" key={key}><b>{label}</b><span>{money(m?.current)} → {money(m?.forecast)}</span><em>{n(m?.probability)}% migration confidence</em></div>})}</section>
       <section className="opex-card"><h3>Magnet-zone probability & attraction</h3><div className="opex-level-line"><span>Primary attraction score</span><b>{n(f.magnet?.attraction_score)}/100</b></div>{(f.magnet?.zone_heatmap||[]).map((z:any)=><div className="opex-zone-row" key={z.band}><b>{z.band}</b><span>{money(z.low)} — {money(z.high)}</span><em>Probability mass {n(z.probability)}% · attraction {n(z.attraction_score)}/100</em></div>)}<div className="opex-subtitle">Top strike attractions</div>{(f.magnet?.candidates||[]).map((m:any)=><Bar key={m.price} label={money(m.price)} value={m.probability}/>)}</section>
      </div>

      <section className="opex-card"><h3>Current-to-target path ladder</h3><div className="opex-table-wrap"><table><thead><tr><th>Step</th><th>Level / zone</th><th>Price</th><th>Probability</th><th>State</th></tr></thead><tbody>{(f.path_distribution?.ladder||[]).map((r:any)=><tr key={`${r.step}-${r.label}`}><td>{r.step}</td><td>{String(r.label||'').replaceAll('_',' ')}</td><td>{r.zone?`${money(r.zone.low)} — ${money(r.zone.high)}`:money(r.price)}</td><td>{n(r.probability)}%</td><td>{String(r.state||'').replaceAll('_',' ')}</td></tr>)}</tbody></table></div></section>

      <div className="opex-grid two">
        <section className="opex-card"><h3>Futures confirmation</h3><div className="opex-level-line"><span>Contract</span><b>{f.futures_confirmation?.product_code||'—'} · {f.futures_confirmation?.ticker||'—'}</b></div><div className="opex-level-line"><span>State</span><b>{f.futures_confirmation?.state||'UNAVAILABLE'} · {n(f.futures_confirmation?.score)}%</b></div><div className="opex-level-line"><span>Dealer / futures interaction</span><b>{String(f.futures_confirmation?.dealer_interaction||'—').replaceAll('_',' ')}</b></div><div className="opex-level-line"><span>Last / VWAP</span><b>{money(f.futures_confirmation?.last_price)} / {money(f.futures_confirmation?.vwap)}</b></div><div className="opex-level-line"><span>Overnight H / L</span><b>{money(f.futures_confirmation?.overnight_high)} / {money(f.futures_confirmation?.overnight_low)}</b></div><div className="opex-level-line"><span>RTH H / L</span><b>{money(f.futures_confirmation?.rth_high)} / {money(f.futures_confirmation?.rth_low)}</b></div><div className="opex-level-line"><span>Basis</span><b>{f.futures_confirmation?.basis_pct==null?'—':`${n(f.futures_confirmation?.basis_pct,3)}%`}</b></div></section>
        <section className="opex-card"><h3>Staged path objectives</h3>{(f.staged_path_objectives||[]).map((x:any)=><div className="opex-migration" key={x.stage}><b>Stage {x.stage}</b><span>{money(x.low)} — {money(x.high)}</span><em>{n(x.conditional_probability)}% conditional probability</em></div>)}</section>
      </div>

      <div className="opex-grid two"><section className="opex-card"><h3>Structural vs tactical dealer positioning</h3><div className="opex-level-line"><span>Target-expiry pressure</span><b>{n(f.dealer?.pressure_score)} · {f.dealer?.direction}</b></div><div className="opex-level-line"><span>0DTE / near-term pressure</span><b>{n(f.dealer?.tactical_0dte_near_term?.pressure_score)} · {f.dealer?.tactical_0dte_near_term?.direction}</b></div><div className="opex-level-line"><span>Position change inference</span><b>{String(f.dealer?.position_change?.state||'—').replaceAll('_',' ')}</b></div><div className="opex-level-line"><span>OI change</span><b>{money(f.dealer?.position_change?.open_interest_change)}</b></div><div className="opex-level-line"><span>Inference confidence</span><b>{n(f.dealer?.position_change?.confidence)}%</b></div></section><section className="opex-card"><h3>Cross-index confirmation</h3><div className="opex-level-line"><span>State</span><b>{String(f.cross_index_confirmation?.state||'—').replaceAll('_',' ')}</b></div><div className="opex-level-line"><span>Confirmation score</span><b>{n(f.cross_index_confirmation?.score)}%</b></div><div className="opex-level-line"><span>Market breadth</span><b>{n(f.market_context?.breadth_score)}</b></div><div className="opex-level-line"><span>Breadth regime</span><b>{String(f.market_context?.breadth_regime||'—').replaceAll('_',' ')}</b></div>{Object.entries(f.cross_index_confirmation?.components?.index_trend_scores||{}).map(([k,v]:any)=><div className="opex-level-line" key={k}><span>{k} trend</span><b>{n(v)}</b></div>)}</section></div>

      <section className="opex-card"><h3>Expected day-by-day path into OPEX</h3><div className="opex-table-wrap"><table><thead><tr><th>Date</th><th>State</th><th>P25</th><th>Median</th><th>P75</th><th>Modeled path zone</th><th>Drivers</th><th>Event move</th></tr></thead><tbody>{(f.expected_daily_path||[]).map((r:any)=><tr key={r.date}><td>{r.date}</td><td>{String(r.state||'').replaceAll('_',' ')}</td><td>{money(r.p25)}</td><td>{money(r.median??r.expected)}</td><td>{money(r.p75)}</td><td>{money(r.low)} — {money(r.high)}</td><td>{(r.drivers||[]).join(', ')||'—'}</td><td>{n(r.event_move_pct)}%</td></tr>)}</tbody></table></div></section>

      <section className="opex-card"><h3>Expected charm & vanna flow by day</h3><div className="opex-table-wrap"><table><thead><tr><th>Date</th><th>Day</th><th>Charm exposure</th><th>Charm index</th><th>Vanna exposure</th><th>Vanna index</th></tr></thead><tbody>{(f.daily_flows||[]).map((r:any)=><tr key={r.trading_day}><td>{r.date}</td><td>{r.trading_day}</td><td>{money(r.charm_exposure)}</td><td>{n(r.charm_index)}</td><td>{money(r.vanna_exposure)}</td><td>{n(r.vanna_index)}</td></tr>)}</tbody></table></div></section>

      <div className="opex-grid two"><section className="opex-card"><h3>Confidence decomposition</h3>{Object.entries(f.confidence?.components||{}).map(([k,v]:any)=><Bar key={k} label={k.replaceAll('_',' ')} value={Number(v)}/>)}</section><section className="opex-card"><h3>Why is the range this wide?</h3>{Object.entries(f.range_width_contributors||{}).map(([k,v]:any)=><Bar key={k} label={k.replaceAll('_',' ')} value={Number(v)}/>)}</section></div>

      <div className="opex-grid two"><section className="opex-card"><h3>Event risk through OPEX</h3><Metric label="Events" value={f.event_risk?.event_count||0}/><Metric label="Material events" value={f.event_risk?.material_event_count||0}/><Metric label="Largest forecast move" value={`${n(f.event_risk?.max_forecast_move_pct)}%`}/><Metric label="Aggregate event uncertainty" value={`${n(f.event_risk?.aggregate_forecast_move_pct)}%`}/>{(f.event_risk?.events||[]).slice(0,8).map((e:any)=><div className="opex-event" key={`${e.type}-${e.date}`}><b>{e.type}</b><span>{e.date} · {e.name||''} · weight {n((e.market_impact_weight||0)*100)}%</span></div>)}</section><section className="opex-card"><h3>Historical OPEX analogs</h3><Metric label="Comparable cycles" value={f.historical_opex_analogs?.sample_size||0}/><Metric label="Median max upside excursion" value={f.historical_opex_analogs?.median_max_excursion_up_pct==null?'—':`${n(f.historical_opex_analogs?.median_max_excursion_up_pct)}%`}/><Metric label="Median max downside excursion" value={f.historical_opex_analogs?.median_max_excursion_down_pct==null?'—':`${n(f.historical_opex_analogs?.median_max_excursion_down_pct)}%`}/><div className="opex-table-wrap"><table><thead><tr><th>Rank</th><th>Expiration</th><th>Similarity</th><th>Settlement</th><th>Max up</th><th>Max down</th></tr></thead><tbody>{(f.historical_opex_analogs?.top_analogs||[]).slice(0,6).map((a:any)=><tr key={a.expiration}><td>{a.rank}</td><td>{a.expiration}</td><td>{n(a.similarity_score)}%</td><td>{n(a.settlement_return_pct)}%</td><td>{n(a.max_upside_excursion_pct)}%</td><td>{n(a.max_downside_excursion_pct)}%</td></tr>)}</tbody></table></div></section></div>

      <section className="opex-card"><h3>Cross-OPEX Transition Map</h3><div className="opex-transition-map">{(cross?.nodes||[]).map((x:any,i:number)=><div className="opex-transition-node" key={x.expiration}><strong>{x.expiration}</strong><span>Magnet {money(x.magnet)}</span><span>Magnet zone {n(x.magnet_zone_probability)}%</span><span>68% terminal {money(x.range68?.low)}–{money(x.range68?.high)}</span><span>Current decision zone {money(x.current_decision_zone?.low)}–{money(x.current_decision_zone?.high)}</span><span>Terminal base zone {money(x.terminal_base_zone?.low)}–{money(x.terminal_base_zone?.high)}</span><span>Gamma flip {money(x.gamma_flip)}</span><span>Pressure {n(x.dealer_pressure)}</span><span>{String(x.dominant_scenario).replaceAll('_',' ')}</span>{i<(cross.nodes.length-1)&&<i>→</i>}</div>)}</div>{(cross?.transitions||[]).map((t:any)=><div className="opex-transition-detail" key={t.from_expiration}><b>{t.from_expiration} → {t.to_expiration}</b><span>Magnet migration {n(t.magnet_migration,2)}</span><span>Gamma-flip migration {n(t.gamma_flip_migration,2)}</span><span>Pressure Δ {n(t.pressure_change,2)}</span><span>Magnet-zone Δ {n(t.magnet_zone_probability_change,2)}</span><span>{t.regime_transition}</span>{(t.transition_probability_matrix||[]).filter((m:any)=>m.from===cross?.nodes?.find((n:any)=>n.expiration===t.from_expiration)?.dominant_scenario).map((m:any)=><div className="opex-transition-probs" key={m.from}>{Object.entries(m.to_probabilities||{}).map(([k,v]:any)=><span key={k}>{String(k).replaceAll('_',' ')} <b>{n(v)}%</b></span>)}</div>)}</div>)}</section>

      <section className="opex-card"><h3>Forecast calibration</h3><div className="opex-metrics"><Metric label="Samples" value={data?.calibration?.sample_size||0}/><Metric label="50% coverage" value={data?.calibration?.coverage50==null?'Pending':`${n(data.calibration.coverage50)}%`}/><Metric label="68% coverage" value={data?.calibration?.coverage68==null?'Pending':`${n(data.calibration.coverage68)}%`}/><Metric label="90% coverage" value={data?.calibration?.coverage90==null?'Pending':`${n(data.calibration.coverage90)}%`}/><Metric label="Actionable range hit" value={data?.calibration?.actionable_range_coverage==null?'Pending':`${n(data.calibration.actionable_range_coverage)}%`}/><Metric label="Magnet-zone hit" value={data?.calibration?.magnet_zone_hit_rate==null?'Pending':`${n(data.calibration.magnet_zone_hit_rate)}%`}/></div></section>
    </>}
  </div>
}
