import { useEffect, useMemo, useState } from 'react';
import { analyticsDashboardApi } from './api';
import { AnalyticsMetric, AnalyticsTable, DetailDrawer, DistributionBars, Histogram, fmt, tone } from './AnalyticsShared';

type ScoreBand={label:string;minimum:number;maximum:number}|null;
const toggle=(current:string|null,next:string)=>current===next?null:next;

export function OptionsMispricingAnalyticsPage(){
 const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<any>(null);const [query,setQuery]=useState('');
 const [classification,setClassification]=useState<string|null>(null);const [strategy,setStrategy]=useState<string|null>(null);const [sector,setSector]=useState<string|null>(null);const [dte,setDte]=useState<string|null>(null);const [moneyness,setMoneyness]=useState<string|null>(null);const [regime,setRegime]=useState<string|null>(null);const [edgeBand,setEdgeBand]=useState<ScoreBand>(null);const [sortDriver,setSortDriver]=useState<string|null>(null);
 useEffect(()=>{
  const controller=new AbortController();setError('');
  analyticsDashboardApi.optionsMispricing(10000,controller.signal).then(response=>{if(!controller.signal.aborted){setData(response.data);setError('')}}).catch(reason=>{if(controller.signal.aborted||(reason instanceof DOMException&&reason.name==='AbortError'))return;setError(reason instanceof Error?reason.message:String(reason))});
  return()=>controller.abort();
 },[]);
 const candidates=data?.candidates??[];
 const filtered=useMemo(()=>{
   const rows=candidates.filter((row:any)=>(!query||row.symbol.toLowerCase().includes(query.toLowerCase())||String(row.company_name??'').toLowerCase().includes(query.toLowerCase()))&&(!classification||row.classification===classification)&&(!strategy||row.strategy===strategy)&&(!sector||row.sector===sector)&&(!dte||row.dte_bucket===dte)&&(!moneyness||row.moneyness_bucket===moneyness)&&(!regime||row.market_regime===regime)&&(!edgeBand||(Number(row.edge_score)>=edgeBand.minimum&&Number(row.edge_score)<edgeBand.maximum)||(edgeBand?.maximum===100&&Number(row.edge_score)===100)));
   if(!sortDriver)return rows;
   return [...rows].sort((a,b)=>Number(b.components?.[sortDriver]??-Infinity)-Number(a.components?.[sortDriver]??-Infinity));
 },[candidates,query,classification,strategy,sector,dte,moneyness,regime,edgeBand,sortDriver]);
 const clear=()=>{setClassification(null);setStrategy(null);setSector(null);setDte(null);setMoneyness(null);setRegime(null);setEdgeBand(null);setSortDriver(null)};
 const active=[edgeBand&&`Edge ${edgeBand.label}`,classification&&`Class ${classification}`,strategy&&`Strategy ${strategy}`,sector&&`Sector ${sector}`,dte&&`DTE ${dte}`,moneyness&&`Moneyness ${moneyness}`,regime&&`Regime ${regime}`,sortDriver&&`Sorted by ${sortDriver}`].filter(Boolean) as string[];
 if(error)return <section className="analytics-page"><p className="provider-warning">{error}</p></section>;
 if(!data)return <section className="analytics-page"><p>Loading governed option-mispricing analytics…</p></section>;
 const summary=data.summary??{};
 return <section className="analytics-page"><div className="analytics-page-title"><div><span className="eyebrow">Analytics</span><h2>Options Mispricing</h2><p>Independent fair value, edge attribution, strategy concentration, execution quality, and candidate-level lineage.</p></div><div className="publication-chip"><span>{summary.status}</span><strong>{summary.publication_id}</strong><small>{summary.published_at}</small></div></div>
 <div className="analytics-metric-grid"><AnalyticsMetric label="Contracts valued" value={fmt(summary.contracts_valued,0)}/><AnalyticsMetric label="Underpriced" value={fmt(summary.underpriced,0)}/><AnalyticsMetric label="Overpriced" value={fmt(summary.overpriced,0)}/><AnalyticsMetric label="Fair value" value={fmt(summary.fair_value,0)}/><AnalyticsMetric label="Average edge score" value={fmt(summary.average_edge_score,2)}/><AnalyticsMetric label="Positive EV" value={fmt(summary.positive_ev,0)}/><AnalyticsMetric label="Executable" value={fmt(summary.executable,0)}/></div>
 <div className="analytics-grid analytics-grid-wide"><Histogram title="Edge score distribution" rows={data.edge_histogram??[]} selected={edgeBand?.label??null} onSelect={(row:any)=>setEdgeBand(edgeBand?.label===row.label?null:{label:String(row.label),minimum:Number(row.minimum),maximum:Number(row.maximum)})}/><DistributionBars title="Mispricing classification" rows={data.classification_distribution??[]} selected={classification} onSelect={(row:any)=>setClassification(toggle(classification,String(row.name)))}/></div>
 <div className="analytics-grid"><DistributionBars title="By strategy" rows={data.by_strategy??[]} selected={strategy} onSelect={(row:any)=>setStrategy(toggle(strategy,String(row.name)))}/><DistributionBars title="By sector" rows={data.by_sector??[]} selected={sector} onSelect={(row:any)=>setSector(toggle(sector,String(row.name)))}/><DistributionBars title="By DTE" rows={data.by_dte??[]} selected={dte} onSelect={(row:any)=>setDte(toggle(dte,String(row.name)))}/><DistributionBars title="By moneyness" rows={data.by_moneyness??[]} selected={moneyness} onSelect={(row:any)=>setMoneyness(toggle(moneyness,String(row.name)))}/><DistributionBars title="By market regime" rows={data.by_market_regime??[]} selected={regime} onSelect={(row:any)=>setRegime(toggle(regime,String(row.name)))}/><DistributionBars title="Average edge attribution" rows={data.driver_averages??[]} valueLabel="average" selected={sortDriver} onSelect={(row:any)=>setSortDriver(toggle(sortDriver,String(row.name)))}/></div>
 <section className="analytics-panel"><header className="table-header"><div><h3>Mispricing candidates</h3><p>{filtered.length} valuation snapshots</p></div><div className="analytics-filters"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search symbol or company"/></div></header>{active.length>0&&<div className="analytics-active-filters">{active.map(label=><span className="analytics-filter-chip" key={label}>{label}</span>)}<button className="analytics-clear-filters" onClick={clear}>Clear chart filters</button></div>}<AnalyticsTable rows={filtered.slice(0,1500)} onSelect={setSelected} columns={[{key:'symbol',label:'Symbol'},{key:'company_name',label:'Company'},{key:'classification',label:'Classification',render:r=><span className={`analytics-badge ${tone(r.classification)}`}>{r.classification}</span>},{key:'strategy',label:'Strategy'},{key:'sector',label:'Sector'},{key:'market_regime',label:'Regime'},{key:'moneyness_bucket',label:'Moneyness'},{key:'dte',label:'DTE',render:r=>fmt(r.dte,0)},{key:'market_mid',label:'Market',render:r=>fmt(r.market_mid,3)},{key:'fair_value',label:'Fair value',render:r=>fmt(r.fair_value,3)},{key:'mispricing_pct',label:'Mispricing %',render:r=><strong>{fmt(r.mispricing_pct,2)}</strong>},{key:'edge_score',label:'Edge',render:r=>fmt(r.edge_score,2)},{key:'calibrated_probability',label:'Probability',render:r=>r.calibrated_probability==null?'—':fmt(r.calibrated_probability,2)},{key:'expected_value',label:'EV',render:r=>r.expected_value==null?'—':fmt(r.expected_value,3)},{key:'expected_return_on_risk',label:'Exp ROR',render:r=>r.expected_return_on_risk==null?'—':fmt(r.expected_return_on_risk,3)},{key:'liquidity_score',label:'Liquidity',render:r=>fmt(r.liquidity_score,1)},{key:'stability_index',label:'Stability',render:r=>fmt(r.stability_index,1)},{key:'executable',label:'Executable',render:r=>r.executable?'YES':'NO'}]}/></section>
 {selected&&<DetailDrawer title={`${selected.symbol} option valuation`} row={selected} onClose={()=>setSelected(null)}/>}</section>;
}
