import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, BrainCircuit, CheckCircle2, RefreshCw, ShieldCheck, SlidersHorizontal, Target, TrendingDown, TrendingUp } from 'lucide-react';
import { performanceLearningApi } from './api';
import type { LearningPolicy, LearningReport, PerformanceMetrics } from './types';
import './performance-learning-refined.css';

const PORTFOLIO_ID = 'PAPER-PRIMARY';
const pct = (v: number, digits = 1) => `${Number(v || 0).toFixed(digits)}%`;
const num = (v: number, digits = 2) => Number(v || 0).toFixed(digits);
const tone = (v: number) => v > 0 ? 'positive' : v < 0 ? 'negative' : 'neutral';
const policyTone = (state: string) => ({ ACTIVE:'positive', APPROVED:'info', REVIEW:'warning', DRAFT:'neutral', RETIRED:'muted' }[state] || 'neutral');

function MetricCard({label,value,detail,kind='neutral'}:{label:string;value:string;detail:string;kind?:string}){
  return <article className={`pl-kpi ${kind}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>;
}
function Bar({value,max=100}:{value:number;max?:number}){
  const width=Math.max(0,Math.min(100,(Number(value||0)/max)*100));
  return <div className="pl-bar"><i style={{width:`${width}%`}} /></div>;
}
function StrategyRow({name,metrics}:{name:string;metrics:PerformanceMetrics}){
  return <tr><td><strong>{name}</strong><small>{metrics.sample_size} observations</small></td><td>{pct(metrics.win_rate)}</td><td className={tone(metrics.expectancy_pct)}>{pct(metrics.expectancy_pct)}</td><td>{num(metrics.profit_factor)}</td><td className={tone(metrics.average_return_pct)}>{pct(metrics.average_return_pct)}</td><td>{pct(metrics.max_drawdown_pct)}</td></tr>;
}

export function PerformanceLearningRefinedPage(){
  const [report,setReport]=useState<LearningReport|null>(null);
  const [policies,setPolicies]=useState<LearningPolicy[]>([]);
  const [busy,setBusy]=useState(false);
  const [cycleBusy,setCycleBusy]=useState(false);
  const [error,setError]=useState('');
  const [strategyQuery,setStrategyQuery]=useState('');
  const [activeTab,setActiveTab]=useState<'performance'|'calibration'|'learning'|'governance'>('performance');
  const [selectedPolicy,setSelectedPolicy]=useState<LearningPolicy|null>(null);
  const [learning,setLearning]=useState<any>(null);

  const load=async()=>{setError('');try{const [r,p,l]=await Promise.all([performanceLearningApi.report(PORTFOLIO_ID),performanceLearningApi.policies(),performanceLearningApi.learningDashboard(PORTFOLIO_ID)]);setReport(r.data);setPolicies(p.data||[]);setLearning(l.data||null)}catch(e){setError(e instanceof Error?e.message:'Unable to load performance analytics')}};
  useEffect(()=>{void load()},[]);
  const generate=async()=>{setBusy(true);setError('');try{const r=await performanceLearningApi.generate(PORTFOLIO_ID);setReport(r.data);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to generate report')}finally{setBusy(false)}};
  const runLearningCycle=async()=>{setCycleBusy(true);setError('');try{await performanceLearningApi.runLearningCycle(PORTFOLIO_ID);const r=await performanceLearningApi.generate(PORTFOLIO_ID);setReport(r.data);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to run learning cycle')}finally{setCycleBusy(false)}};

  const strategies=useMemo(()=>Object.entries(report?.by_strategy||{}).filter(([name])=>name.toLowerCase().includes(strategyQuery.toLowerCase())).sort((a,b)=>b[1].expectancy_pct-a[1].expectancy_pct),[report,strategyQuery]);
  const best=strategies[0]; const worst=strategies.length?strategies[strategies.length-1]:undefined;
  const dq=report?.decision_quality;
  const calibrationError=report?.calibration?.length?report.calibration.reduce((a,b)=>a+(b.calibration_error||0),0)/report.calibration.length:0;
  const command=(report?.command_center||{}) as any; const exec=command.execution_quality||{}; const mgmt=command.management_effectiveness||{}; const portfolioLearning=command.portfolio_allocation_learning||{}; const calMetrics=command.calibration_metrics||{};

  return <section className="pl-page">
    <header className="pl-heading"><div><span className="pl-eyebrow">Institutional evidence center · {PORTFOLIO_ID}</span><h2>Performance Command Center</h2><p>Measure realized performance, probability calibration, OPEX forecast quality, execution edge preservation and governed learning evidence without autonomous model activation.</p></div><div className="pl-actions"><button className="secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button><button className="secondary" onClick={runLearningCycle} disabled={cycleBusy}><Activity size={16}/>{cycleBusy?'Learning…':'Run learning cycle'}</button><button onClick={generate} disabled={busy}><BrainCircuit size={16}/>{busy?'Generating…':'Generate governed report'}</button></div></header>
    {error&&<div className="pl-error"><AlertTriangle size={18}/><span>{error}</span></div>}
    {!report?<div className="pl-empty"><BarChart3 size={34}/><h3>No performance report yet</h3><p>Generate a governed report after managed-position observations have been captured.</p></div>:<>
      <div className="pl-kpis">
        <MetricCard label="Observations" value={String(report.overall.sample_size)} detail={`${report.overall.wins} wins · ${report.overall.losses} losses`} />
        <MetricCard label="Win rate" value={pct(report.overall.win_rate)} detail={`Median return ${pct(report.overall.median_return_pct)}`} kind={report.overall.win_rate>=50?'positive':'warning'} />
        <MetricCard label="Expectancy" value={pct(report.overall.expectancy_pct)} detail={`Average ${pct(report.overall.average_return_pct)}`} kind={tone(report.overall.expectancy_pct)} />
        <MetricCard label="Profit factor" value={num(report.overall.profit_factor)} detail="Gross profit ÷ gross loss" kind={report.overall.profit_factor>=1?'positive':'negative'} />
        <MetricCard label="Max drawdown" value={pct(report.overall.max_drawdown_pct)} detail="Observed portfolio path" kind="warning" />
        <MetricCard label="Decision alignment" value={pct(dq?.alignment_rate||0)} detail={`${pct(dq?.override_rate||0)} override rate`} kind={(dq?.alignment_rate||0)>=70?'positive':'warning'} />
      </div>
      {command.policy_version&&<section className="pl-card pl-wide"><header><div><h3>Performance foundation (M65)</h3><p>Outcome reconstruction, calibration, execution, management, portfolio-allocation and counterfactual learning feeding the M72 evidence center.</p></div><span className="pl-chip info">{command.policy_version}</span></header><div className="pl-stat-list"><div><span>Brier score</span><b>{num(calMetrics.brier_score||0,4)}</b></div><div><span>Expected calibration error</span><b>{pct((calMetrics.expected_calibration_error||0)*100)}</b></div><div><span>Fill rate</span><b>{pct(exec.fill_rate_pct||0)}</b></div><div><span>Total commissions</span><b>${num(exec.total_commission||0)}</b></div><div><span>Management avg return</span><b className={tone(mgmt.average_return_pct||0)}>{pct(mgmt.average_return_pct||0)}</b></div><div><span>Portfolio-fit samples</span><b>{portfolioLearning.sample_size||0}</b></div></div></section>}
      <nav className="pl-tabs"><button className={activeTab==='performance'?'active':''} onClick={()=>setActiveTab('performance')}><Activity size={16}/>Performance</button><button className={activeTab==='calibration'?'active':''} onClick={()=>setActiveTab('calibration')}><Target size={16}/>Calibration & decisions</button><button className={activeTab==='learning'?'active':''} onClick={()=>setActiveTab('learning')}><BrainCircuit size={16}/>Outcome learning</button><button className={activeTab==='governance'?'active':''} onClick={()=>setActiveTab('governance')}><ShieldCheck size={16}/>Learning governance</button></nav>
      {activeTab==='performance'&&<div className="pl-grid">
        <section className="pl-card pl-wide"><header><div><h3>Strategy attribution</h3><p>Ranked by realized expectancy.</p></div><label className="pl-search"><SlidersHorizontal size={15}/><input value={strategyQuery} onChange={e=>setStrategyQuery(e.target.value)} placeholder="Filter strategies"/></label></header><div className="pl-table-wrap"><table><thead><tr><th>Strategy</th><th>Win rate</th><th>Expectancy</th><th>Profit factor</th><th>Avg return</th><th>Drawdown</th></tr></thead><tbody>{strategies.map(([name,m])=><StrategyRow key={name} name={name} metrics={m}/>)}</tbody></table></div></section>
        <section className="pl-card"><header><h3>Performance leaders</h3><TrendingUp size={18}/></header>{best?<div className="pl-highlight positive"><span>Highest expectancy</span><strong>{best[0]}</strong><b>{pct(best[1].expectancy_pct)}</b><small>{best[1].sample_size} observations · {pct(best[1].win_rate)} win rate</small></div>:<p className="pl-muted">No strategy samples.</p>}{worst&&worst!==best&&<div className="pl-highlight negative"><span>Needs review</span><strong>{worst[0]}</strong><b>{pct(worst[1].expectancy_pct)}</b><small>{worst[1].sample_size} observations · PF {num(worst[1].profit_factor)}</small></div>}</section>
        <section className="pl-card"><header><h3>Directional attribution</h3><Activity size={18}/></header>{Object.entries(report.by_direction||{}).map(([name,m])=><div className="pl-direction" key={name}><div><strong>{name}</strong><span>{m.sample_size} samples</span></div><b className={tone(m.expectancy_pct)}>{pct(m.expectancy_pct)}</b><Bar value={m.win_rate}/><small>{pct(m.win_rate)} win rate · PF {num(m.profit_factor)}</small></div>)}</section>
      </div>}
      {activeTab==='calibration'&&<div className="pl-grid">
        <section className="pl-card pl-wide"><header><div><h3>Probability calibration</h3><p>Predicted probability versus observed win rate.</p></div><span className={`pl-chip ${calibrationError>.1?'warning':'positive'}`}>Mean error {pct(calibrationError*100)}</span></header><div className="pl-calibration">{report.calibration.map((b,i)=>{const predicted=b.predicted*100,observed=b.observed*100;return <article key={i}><header><strong>{Math.round(b.lower*100)}–{Math.round(b.upper*100)}%</strong><span>N {b.count}</span></header><div className="pl-cal-row"><label>Predicted <b>{pct(predicted)}</b></label><Bar value={predicted}/></div><div className="pl-cal-row"><label>Observed <b>{pct(observed)}</b></label><Bar value={observed}/></div><small className={b.calibration_error>.1?'negative':'positive'}>Calibration error {pct(b.calibration_error*100)}</small></article>})}</div></section>
        <section className="pl-card"><header><h3>Decision quality</h3><CheckCircle2 size={18}/></header><div className="pl-stat-list"><div><span>Alignment rate</span><b>{pct(dq?.alignment_rate||0)}</b></div><div><span>Manual overrides</span><b>{pct(dq?.override_rate||0)}</b></div><div><span>Profitable alignment</span><b>{pct(dq?.profitable_alignment_rate||0)}</b></div><div><span>Avoidable loss rate</span><b className="negative">{pct(dq?.avoidable_loss_rate||0)}</b></div><div><span>Evaluated decisions</span><b>{dq?.sample_size||0}</b></div></div></section>
        <section className="pl-card"><header><h3>Governed recommendations</h3><BrainCircuit size={18}/></header><div className="pl-recommendations">{report.recommendations.length?report.recommendations.map((r,i)=><article key={`${r.target}-${i}`}><span className="pl-chip info">{r.category}</span><strong>{r.target}</strong><p>{r.reason}</p><div><b>{r.current_value}</b><span>→</span><b>{r.proposed_value}</b></div><small>N {r.sample_size} · confidence {pct(r.confidence*100)}</small></article>):<p className="pl-muted">No parameter changes are currently recommended.</p>}</div></section>
        <section className="pl-card pl-wide"><header><div><h3>M72 segmented calibration health</h3><p>Newest reliability evidence for every model, source, strategy, symbol and regime segment.</p></div><span className="pl-chip info">{learning?.calibration?.health?.reviewable||0} reviewable</span></header><div className="pl-stat-list"><div><span>Calibration segments</span><b>{learning?.calibration?.health?.segments||0}</b></div><div><span>Reviewable (N ≥ 50)</span><b>{learning?.calibration?.health?.reviewable||0}</b></div><div><span>Developing (N 30–49)</span><b>{learning?.calibration?.health?.developing||0}</b></div><div><span>Insufficient sample</span><b>{learning?.calibration?.health?.insufficient_sample||0}</b></div></div><div className="pl-table-wrap"><table><thead><tr><th>Scope</th><th>Value</th><th>Target</th><th>N</th><th>Status</th><th>Brier</th><th>ECE</th><th>Bias</th></tr></thead><tbody>{(learning?.calibration?.latest||[]).slice(0,40).map((x:any,i:number)=><tr key={`cal-${x.scope}-${x.scope_value}-${x.target_type}-${i}`}><td>{x.scope}</td><td><strong>{x.scope_value}</strong></td><td>{x.target_type}</td><td>{x.sample_size}</td><td><span className={`pl-chip ${x.health==='REVIEWABLE'?'positive':x.health==='DEVELOPING'?'warning':'muted'}`}>{x.health}</span></td><td>{x.brier_score==null?'—':num(x.brier_score,4)}</td><td>{x.expected_calibration_error==null?'—':pct(x.expected_calibration_error*100,2)}</td><td>{x.calibration_bias==null?'—':`${x.calibration_bias>=0?'+':''}${pct(x.calibration_bias*100,2)}`}</td></tr>)}</tbody></table></div></section>
      </div>}
      {activeTab==='learning'&&<div className="pl-grid">
        <section className="pl-card pl-wide"><header><div><h3>Evidence pipeline health</h3><p>Source evidence flowing into realized trade learning, execution analytics and OPEX calibration. M72.2.1 separates legitimate no-fill / never-routed states from actual evidence gaps.</p></div><span className="pl-chip info">M72.2.1</span></header><div className="pl-stat-list"><div><span>Trade outcomes</span><b>{learning?.evidence_pipeline?.trade?.trade_outcomes||0}</b></div><div><span>Realized trade outcomes</span><b>{learning?.evidence_pipeline?.trade?.realized_trade_outcomes||0}</b></div><div><span>Learning observations</span><b>{learning?.evidence_pipeline?.trade?.learning_observations||0}</b></div><div><span>Unbridged realized trades</span><b>{learning?.evidence_pipeline?.trade?.unbridged_realized_outcomes||0}</b></div><div><span>Execution intents</span><b>{learning?.evidence_pipeline?.execution?.execution_intents||0}</b></div><div><span>Never routed intents</span><b>{learning?.evidence_pipeline?.execution?.never_routed_intents||0}</b></div><div><span>Broker orders</span><b>{learning?.evidence_pipeline?.execution?.broker_orders||0}</b></div><div><span>Filled broker orders</span><b>{learning?.evidence_pipeline?.execution?.filled_broker_orders||0}</b></div><div><span>Broker executions</span><b>{learning?.evidence_pipeline?.execution?.broker_executions||0}</b></div><div><span>Execution telemetry</span><b>{learning?.evidence_pipeline?.execution?.telemetry_rows||0}</b></div><div><span>Routed without telemetry</span><b>{learning?.evidence_pipeline?.execution?.routed_without_telemetry||0}</b></div><div><span>Execution learning samples</span><b>{learning?.evidence_pipeline?.execution?.learning_samples||0}</b></div><div><span>Execution sync state</span><b>{learning?.evidence_pipeline?.execution?.broker_execution_sync_state||'UNKNOWN'}</b></div><div><span>OPEX forecasts</span><b>{learning?.evidence_pipeline?.opex?.forecast_snapshots||0}</b></div><div><span>OPEX realized</span><b>{learning?.evidence_pipeline?.opex?.forecast_outcomes||0}</b></div></div>{learning?.evidence_pipeline?.execution?.needs_ibkr_execution_sync&&<div className="pl-error"><AlertTriangle size={18}/><span>Filled broker-order evidence exists but broker execution history is incomplete. Run <code>uv run python scripts/run_m72_learning_cycle.py --sync-ibkr</code> while TWS/IB Gateway paper session is available.</span></div>}{learning?.evidence_pipeline?.execution?.broker_execution_sync_state==='NO_FILLS_AVAILABLE'&&<p className="pl-muted">No completed fills are currently available to import. Broker execution history is therefore correctly empty.</p>}</section>
        <section className="pl-card pl-wide"><header><div><h3>Prediction registry</h3><p>Immutable trade and OPEX predictions with lineage, probability, model version and realized-outcome status.</p></div><span className="pl-chip info">{learning?.version||'M72'}</span></header><div className="pl-stat-list"><div><span>Registered predictions</span><b>{learning?.prediction_registry?.predictions||0}</b></div><div><span>Realized predictions</span><b>{learning?.prediction_registry?.realized_predictions||0}</b></div><div><span>Realized outcomes</span><b>{learning?.prediction_registry?.realized_outcomes||0}</b></div><div><span>Pending predictions</span><b>{learning?.prediction_registry?.pending||0}</b></div><div><span>Outcome completion</span><b>{pct(learning?.prediction_registry?.completion_rate_pct||0)}</b></div><div><span>Learning mode</span><b>{learning?.governance?.learning_mode||'EVIDENCE ONLY'}</b></div></div><div className="pl-table-wrap"><table><thead><tr><th>Source</th><th>Count</th></tr></thead><tbody>{Object.entries(learning?.prediction_registry?.by_source||{}).map(([k,v]:any)=><tr key={k}><td><strong>{k}</strong></td><td>{v}</td></tr>)}</tbody></table></div></section>
        <section className="pl-card pl-wide"><header><div><h3>Recent prediction → outcome lineage</h3><p>Newest registered forecasts and trade decisions. Pending is expected until the forecast horizon/trade closes.</p></div></header><div className="pl-table-wrap"><table><thead><tr><th>Status</th><th>Source</th><th>Symbol</th><th>Strategy</th><th>Target</th><th>Probability</th><th>Confidence</th><th>Model</th><th>Generated</th></tr></thead><tbody>{(learning?.prediction_registry?.recent||[]).slice(0,30).map((x:any)=><tr key={x.prediction_id}><td><span className={`pl-chip ${x.status==='REALIZED'?'positive':'muted'}`}>{x.status}</span></td><td>{x.source_type}</td><td><strong>{x.symbol}</strong></td><td>{x.strategy||'—'}</td><td>{x.target_type}</td><td>{x.predicted_probability==null?'—':pct(x.predicted_probability*100,1)}</td><td>{x.confidence==null?'—':pct(x.confidence*100,1)}</td><td>{x.model_version}</td><td>{new Date(x.generated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
        <section className="pl-card pl-wide"><header><div><h3>OPEX forecast validation</h3><p>Coverage, scenario, magnet and path accuracy measured against realized SPX/NDX/RUT outcomes.</p></div><span className={`pl-chip ${(learning?.opex_calibration?.sample_size||0)>=30?'positive':'warning'}`}>{learning?.opex_calibration?.status||'INSUFFICIENT_SAMPLE'}</span></header><div className="pl-stat-list"><div><span>Completed forecast samples</span><b>{learning?.opex_calibration?.sample_size||0}</b></div><div><span>50% coverage</span><b>{learning?.opex_calibration?.coverage50==null?'Pending':pct(learning.opex_calibration.coverage50)}</b></div><div><span>68% coverage</span><b>{learning?.opex_calibration?.coverage68==null?'Pending':pct(learning.opex_calibration.coverage68)}</b></div><div><span>90% coverage</span><b>{learning?.opex_calibration?.coverage90==null?'Pending':pct(learning.opex_calibration.coverage90)}</b></div><div><span>Scenario accuracy</span><b>{learning?.opex_calibration?.scenario_accuracy_pct==null?'Pending':pct(learning.opex_calibration.scenario_accuracy_pct)}</b></div><div><span>Magnet-zone hit</span><b>{learning?.opex_calibration?.magnet_zone_hit_rate==null?'Pending':pct(learning.opex_calibration.magnet_zone_hit_rate)}</b></div><div><span>Magnet distance</span><b>{learning?.opex_calibration?.average_magnet_distance_pct==null?'Pending':pct(learning.opex_calibration.average_magnet_distance_pct,2)}</b></div><div><span>Path MAPE</span><b>{learning?.opex_calibration?.path_mape_pct==null?'Pending':pct(learning.opex_calibration.path_mape_pct,2)}</b></div><div><span>P25–P75 path coverage</span><b>{learning?.opex_calibration?.path_band_coverage_pct==null?'Pending':pct(learning.opex_calibration.path_band_coverage_pct)}</b></div><div><span>Path direction</span><b>{learning?.opex_calibration?.path_direction_accuracy_pct==null?'Pending':pct(learning.opex_calibration.path_direction_accuracy_pct)}</b></div></div><div className="pl-table-wrap"><table><thead><tr><th>Index</th><th>N</th><th>50%</th><th>68%</th><th>90%</th><th>Scenario</th><th>Path MAPE</th><th>Path band</th><th>Magnet dist.</th></tr></thead><tbody>{Object.entries(learning?.opex_calibration?.by_symbol||{}).map(([symbol,x]:any)=><tr key={symbol}><td><strong>{symbol}</strong></td><td>{x.sample_size}</td><td>{pct(x.coverage50)}</td><td>{pct(x.coverage68)}</td><td>{pct(x.coverage90)}</td><td>{x.scenario_accuracy_pct==null?'—':pct(x.scenario_accuracy_pct)}</td><td>{x.path_mape_pct==null?'—':pct(x.path_mape_pct,2)}</td><td>{x.path_band_coverage_pct==null?'—':pct(x.path_band_coverage_pct)}</td><td>{x.average_magnet_distance_pct==null?'—':pct(x.average_magnet_distance_pct,2)}</td></tr>)}</tbody></table></div></section>
        <section className="pl-card pl-wide"><header><div><h3>Execution quality & edge preservation</h3><p>Whether predicted edge survives quote drift, routing latency, spread friction, fills and commissions.</p></div><Activity size={18}/></header><div className="pl-stat-list"><div><span>Execution samples</span><b>{learning?.execution_quality?.sample_size||0}</b></div><div><span>Filled</span><b>{learning?.execution_quality?.filled||0}</b></div><div><span>Fill rate</span><b>{pct(learning?.execution_quality?.fill_rate_pct||0)}</b></div><div><span>Quality score</span><b>{num(learning?.execution_quality?.average_quality_score||0,1)}</b></div><div><span>Realized slippage</span><b>{pct(learning?.execution_quality?.average_realized_slippage_pct||0,3)}</b></div><div><span>Edge preservation</span><b>{pct(learning?.execution_quality?.edge_preservation_pct||0)}</b></div><div><span>Execution edge drag</span><b>${num(learning?.execution_quality?.average_execution_edge_drag_dollars||0,2)}</b></div><div><span>Decision → submit</span><b>{num(learning?.execution_quality?.average_decision_to_submit_seconds||0,1)}s</b></div><div><span>Submit → first fill</span><b>{num(learning?.execution_quality?.average_time_to_first_fill_seconds||0,1)}s</b></div><div><span>Commissions</span><b>${num(learning?.execution_quality?.commission_total||0,2)}</b></div></div><div className="pl-table-wrap"><table><thead><tr><th>Strategy</th><th>N</th><th>Quality</th><th>Slippage</th><th>Edge preservation</th></tr></thead><tbody>{Object.entries(learning?.execution_quality?.by_strategy||{}).map(([strategy,x]:any)=><tr key={strategy}><td><strong>{strategy}</strong></td><td>{x.sample_size}</td><td>{num(x.average_quality,1)}</td><td>{pct(x.average_slippage_pct,3)}</td><td>{pct(x.edge_preservation_pct)}</td></tr>)}</tbody></table></div></section>
      </div>}
      {activeTab==='governance'&&<div className="pl-grid">
        <section className="pl-card pl-wide"><header><div><h3>Learning-policy registry</h3><p>Human-controlled lifecycle with immutable evidence and versioned activation.</p></div><span className="pl-chip positive">±15% weight boundary</span></header><div className="pl-table-wrap"><table><thead><tr><th>Policy</th><th>Version</th><th>State</th><th>Owner</th><th>Updated</th></tr></thead><tbody>{policies.map(p=><tr key={p.policy_id} onClick={()=>setSelectedPolicy(p)} className={selectedPolicy?.policy_id===p.policy_id?'selected':''}><td><strong>{p.policy_name}</strong><small>{p.reason}</small></td><td>v{p.version}</td><td><span className={`pl-chip ${policyTone(p.state)}`}>{p.state}</span></td><td>{p.approved_by||p.created_by}</td><td>{new Date(p.updated_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>
        <section className="pl-card"><header><h3>Policy controls</h3><ShieldCheck size={18}/></header><ul className="pl-controls"><li>Explicit human approval before activation</li><li>Only one active version per policy</li><li>Immutable supporting evidence</li><li>Append-only audit events</li><li>No autonomous scanner or model changes</li></ul></section>
        <section className="pl-card"><header><h3>Evidence readiness</h3><CheckCircle2 size={18}/></header><div className="pl-stat-list"><div><span>Reviewable calibration segments</span><b>{learning?.governance?.evidence_readiness?.reviewable_segments||0}</b></div><div><span>Developing segments</span><b>{learning?.governance?.evidence_readiness?.developing_segments||0}</b></div><div><span>Insufficient sample</span><b>{learning?.governance?.evidence_readiness?.insufficient_segments||0}</b></div><div><span>Minimum review sample</span><b>{learning?.governance?.minimum_sample_for_review||30}</b></div><div><span>Segment calibration sample</span><b>{learning?.governance?.minimum_sample_for_segmented_calibration||50}</b></div><div><span>Automatic activation</span><b className="positive">DISABLED</b></div></div></section>
        <section className="pl-card"><header><h3>Selected policy</h3><SlidersHorizontal size={18}/></header>{selectedPolicy?<><div className="pl-policy-title"><strong>{selectedPolicy.policy_name}</strong><span className={`pl-chip ${policyTone(selectedPolicy.state)}`}>{selectedPolicy.state}</span></div><p>{selectedPolicy.reason}</p><div className="pl-json">{Object.entries(selectedPolicy.parameters||{}).map(([k,v])=><div key={k}><span>{k}</span><b>{v}</b></div>)}</div></>:<p className="pl-muted">Select a policy to inspect its governed parameters.</p>}</section>
      </div>}
    </>}
  </section>;
}
