export type Envelope<T=unknown>={status?:string;request_id:string;generated_at?:string;data:T;metadata:Record<string,unknown>};
export type ArtifactState={exists:boolean;stale:boolean;modified_at:string|null;age_seconds:number|null;path:string};
export type Overview=Record<string,ArtifactState>;
export type Health={service:string;milestone:number;status:string};
export type Readiness={ready:boolean;components:Record<string,ArtifactState>};
export type WorkspaceKey='market'|'scanner'|'stock-intelligence'|'option-scanner'|'institutional-options'|'opportunities'|'intelligence'|'trade-builder'|'portfolio'|'risk'|'execution-workspace'|'execution'|'positions'|'exits'|'performance-learning'|'command'|'analytics-inflection'|'analytics-options-mispricing'|'analytics-opex'|'execution-intelligence';
export type RunStatus='QUEUED'|'RUNNING'|'SUCCEEDED'|'FAILED';
export type ScannerRun={run_id:string;kind:'DATA_REFRESH'|'DAILY_SCAN';status:RunStatus;created_at:string;started_at?:string|null;completed_at?:string|null;requested_by:string;request:Record<string,unknown>;exit_code?:number|null;stdout:string;stderr:string;report_date?:string|null;artifacts:Record<string,string>;summary:Record<string,any>};
export type RefreshMode='cache_only'|'refresh_missing'|'force_full';
export type ScannerUniverse={id:string;label:string;description:string;symbol_count:number;source:string;as_of_date?:string|null;maximum_symbols?:number|null;active:boolean};
export type DataRefreshRequest={data_scope:'underlying'|'options'|'all';universe:string;symbols:string[];start:string;end:string;refresh_mode:RefreshMode;minimum_bars:number;stale_after_days:number;minimum_coverage_pct:number;maximum_failed_symbols:number;continue_on_degraded_refresh:boolean;max_retries:number;retry_backoff_seconds:number;maximum_retry_backoff_seconds:number;retry_jitter_ratio:number;rate_limit_cooldown_seconds:number;circuit_breaker_threshold:number;circuit_breaker_cooldown_seconds:number;batch_size:number};
export type DailyScanRequest={universe:string;symbols:string[];start:string;end:string;minimum_score:number;top:number;pricing_dte:number;expiration_mode:'automatic'|'short'|'swing'|'medium'|'long'|'custom'|'fixed';minimum_dte:number;maximum_dte:number;maximum_expirations_per_symbol:number;maximum_trades_per_expiration:number;option_data_mode:'live'|'auto'|'proxy';liquidity_data_mode:'adaptive'|'strict';maximum_option_spread_pct:number;minimum_option_open_interest:number;minimum_option_volume:number;capital:number;risk_per_trade_pct:number;max_position_pct:number;take_profit_pct:number;stop_loss_pct:number;direction?:'both'|'bullish'|'bearish';minimum_trend_quality_score?:number;minimum_trend_alignment_score?:number;minimum_trend_confidence?:number;allowed_trend_stages?:string[];minimum_transition_confirmation_score?:number;maximum_reversal_risk_score?:number;maximum_exhaustion_risk_score?:number;require_breakout?:boolean;require_fresh_dealer_context?:boolean;minimum_dealer_score_adjustment?:number;minimum_market_structure_confidence?:number;minimum_participation_score?:number;minimum_leadership_score?:number;minimum_institutional_conviction_score?:number;maximum_deterioration_risk_score?:number;minimum_breadth_confirmation_score?:number;minimum_cross_asset_confirmation_score?:number;refresh_mode:RefreshMode;auto_refresh:boolean;minimum_refresh_coverage_pct:number;maximum_failed_refresh_symbols:number;continue_on_degraded_refresh:boolean;refresh_max_retries:number;refresh_retry_backoff_seconds:number;refresh_maximum_retry_backoff_seconds:number;refresh_retry_jitter_ratio:number;refresh_rate_limit_cooldown_seconds:number;refresh_circuit_breaker_threshold:number;refresh_circuit_breaker_cooldown_seconds:number};
export type ScannerResults={run:ScannerRun;recommendations:{metadata?:Record<string,any>;candidates?:any[]};trades:{metadata?:Record<string,any>;trades?:any[]}};

export type OpportunityWorkflowState='STAGED'|'UNDER_REVIEW'|'APPROVED'|'REJECTED'|'TRADE_BUILT'|'PAPER_SUBMITTED'|'ARCHIVED';
export type OpportunityRecord={opportunity_id:string;scanner_run_id:string;snapshot_id:string;snapshot_timestamp:string;symbol:string;direction:string;strategy:string;workflow_state:OpportunityWorkflowState;version:number;source_payload:Record<string,any>;created_by:string;created_at:string;updated_at:string;metadata:Record<string,any>};
export type OpportunityEvent={event_id:string;opportunity_id:string;opportunity_version:number;event_type:string;previous_state:string|null;new_state:string;actor:string;reason:string;event_timestamp:string;metadata:Record<string,any>};
export type StageOpportunityRequest={scanner_run_id:string;snapshot_id:string;snapshot_timestamp:string;symbol:string;direction:string;strategy:string;source_payload:Record<string,any>;metadata?:Record<string,any>};

export type IntelligenceEvidence={source:string;title:string;description:string;score:number;weight:number;contribution:number;confidence:number;severity:string};
export type IntelligenceScore={category:string;name:string;overall_score:number;confidence:number;percentile:number;trend:string;status:string;severity:string;evidence:IntelligenceEvidence[];risks:any[];recommendations:any[];metrics:Record<string,any>};
export type IntelligenceBundle={opportunity_id:string;snapshot_id:string;snapshot_timestamp:string;analytics_version:string;generated_at:string;scores:IntelligenceScore[];explanation:{summary:string;confidence:number;positive_drivers:IntelligenceEvidence[];negative_drivers:IntelligenceEvidence[];invalidation_conditions:string[];checklist:{category:string;label:string;passed:boolean;score:number}[]};recommendations:any[];playbook:{preferred_strategy:string;alternative_strategy:string;entry:number|null;stop:number|null;targets:number[];expected_hold_days:number;probability:number;position_size_pct:number;contracts:number|null;greeks:Record<string,any>;risk_notes:string[]};health:{score:number;direction:string;baseline_score:number;drivers:{category:string;score:number;direction:string}[];recommended_action:string};profile:Record<string,string>};

export type TradePlan={trade_plan_id:string;opportunity_id:string;opportunity_version:number;intelligence_id:string|null;account_id:string;symbol:string;direction:string;strategy:string;state:string;version:number;capital:number;risk_budget_pct:number;risk_budget_amount:number;estimated_debit:number;estimated_credit:number;max_loss:number;max_profit:number|null;reward_risk_ratio:number|null;net_greeks:Record<string,number>;validation:Record<string,any>;legs:any[];created_by:string;created_at:string;updated_at:string;notes:string;execution_intent:Record<string,any>;actions?:any[];available_actions?:any[];actionable?:boolean};

export type PositionHealthDriver={category:string;score:number;direction:string;contribution:number;reason:string};export type ManagedPosition={position_id:string;portfolio_id:string;trade_plan_id:string;opportunity_id:string;intelligence_id:string|null;execution_id:string|null;symbol:string;strategy:string;direction:string;state:string;version:number;opened_at:string;closed_at:string|null;entry_value:number;realized_pnl:number;mark:{mark_price:number;quantity:number;market_value:number;unrealized_pnl:number;unrealized_return_pct:number;delta:number;gamma:number;theta:number;vega:number;days_to_expiry:number|null};health:{score:number;direction:string;confidence:number;drivers:PositionHealthDriver[];alerts:string[]};decision:{action:string;confidence:number;priority:string;reason:string;expected_benefit:string;risk_impact:string;alternatives:string[]};metadata:Record<string,any>};export type PortfolioIntelligenceSnapshot={snapshot_id?:string;portfolio_id:string;snapshot_timestamp:string;net_liquidation:number;cash:number;buying_power:number;market_value:number;unrealized_pnl:number;realized_pnl:number;open_risk:number;health_score:number;position_count:number;greeks:Record<string,number>;sector_exposure:Record<string,number>;strategy_exposure:Record<string,number>;concentration:Record<string,number>};

export type PerformanceMetrics={sample_size:number;wins:number;losses:number;flats:number;win_rate:number;average_return_pct:number;median_return_pct:number;profit_factor:number;expectancy_pct:number;max_drawdown_pct:number};export type LearningReport={report_id:string;portfolio_id:string;generated_at:string;overall:PerformanceMetrics;by_strategy:Record<string,PerformanceMetrics>;by_direction:Record<string,PerformanceMetrics>;calibration:{lower:number;upper:number;count:number;predicted:number;observed:number;calibration_error:number}[];decision_quality:{alignment_rate:number;override_rate:number;profitable_alignment_rate:number;avoidable_loss_rate:number;sample_size:number};recommendations:{category:string;target:string;current_value:number;proposed_value:number;confidence:number;sample_size:number;reason:string;evidence:Record<string,any>}[];governance:Record<string,any>;command_center?:Record<string,any>};export type LearningPolicy={policy_id:string;policy_name:string;version:number;state:string;parameters:Record<string,number>;evidence:Record<string,any>;reason:string;created_by:string;approved_by:string|null;created_at:string;updated_at:string;activated_at:string|null};


export type ExecutionIntent={execution_intent_id:string;trade_plan_id:string;trade_plan_version:number;execution_attempt?:number;parent_execution_intent_id?:string|null;retry_reason?:string|null;retryable?:boolean;opportunity_id:string;portfolio_id:string;account_id:string;symbol:string;strategy:string;state:string;version:number;legs:any[];order_request:Record<string,any>;validation:{valid:boolean;checks:Record<string,boolean>;warnings:string[];estimated_notional:number;max_loss:number;buying_power:number|null};broker:Record<string,any>;created_by:string;created_at:string;updated_at:string;submitted_at:string|null;terminal_at:string|null;metadata:Record<string,any>};
export type ExecutionIntentAudit={event_id:string;execution_intent_version:number;event_type:string;previous_state:string|null;new_state:string;actor:string;reason:string;event_timestamp:string;payload:Record<string,any>};
export type StockIntelligenceCandidate={candidate_id:string;symbol:string;rank:number|null;primary_category:string;score:number;confidence:number;freshness:number;direction:string;structure:string;primary_timeframe:string;alignment_score:number;participation_state:string;institutional_volume_score:number;institutional_volume_regime:string;institutional_volume_signal:string;relative_volume_1d:number;volume_persistence_score:number;volume_dry_up_score:number;volume_absorption_score:number;breakout_volume_confirmation:number;breakdown_volume_confirmation:number;breakout_state:string;relative_strength_grade:string;dealer_positioning:string;gamma_regime:string;market_regime:string;underlying_reference_price?:number|null;underlying_reference_timestamp?:string|null;underlying_reference_source?:string|null;underlying_reference_freshness_minutes?:number|null;trade_plan_certification?:Record<string,any>;trade_plan_certification_status?:string;trade_plan_quality_score?:number|null;institutional_trade_quality?:number|null;decision_readiness?:number|null;capital_priority?:number|null;opportunity_freshness?:number|null;institutional_grade?:string|null;institutional_decision?:string|null;opportunity_lifecycle?:string|null;barrier_target_1_probability?:number|null;barrier_target_2_probability?:number|null;barrier_target_3_probability?:number|null;expected_mfe_pct?:number|null;expected_mae_pct?:number|null;decision_market_rank?:number|null;decision_population_size?:number|null;decision_market_percentile?:number|null;decision_intelligence?:Record<string,any>;outcome_probability_status?:string|null;outcome_probability_disposition?:string|null;outcome_probability_target_1?:number|null;outcome_probability_target_2?:number|null;outcome_probability_profitable_horizon?:number|null;outcome_probability_expected_value_r?:number|null;outcome_probability_uncertainty?:number|null;outcome_probability?:Record<string,any>;entry_zone_low:number|null;entry_zone_high:number|null;recommended_stop:number|null;targets:(number|null)[];additional_targets:any[];structural_reward_risk:number;management_quality:number;timeframes:Record<string,{direction:string;structure:string;confidence:number}>;snapshot_timestamp:string;state_hash:string;warnings:string[]};

export type InstitutionalOptionOpportunitySummary={
  opportunity_id:string;symbol:string;asset_class:string;state:string;direction:string;category:string;
  overall_score:number;confidence:number;conviction:string;version:number;created_at:string;updated_at:string;
  best_strategy?:string|null;best_strategy_score?:number|null;calibrated_probability?:number|null;
  expected_value?:number|null;expected_return_on_risk?:number|null;ready_for_trade_builder?:boolean;
  institutional_plan_certification?:Record<string,any>;institutional_plan_certification_status?:string|null;institutional_plan_fingerprint?:string|null;
  underlying_stop?:number|null;underlying_targets?:number[];metadata?:Record<string,any>;lineage?:Record<string,any>;
  display_state?:string;next_governed_action?:string;lifecycle_authority?:Record<string,any>;
  portfolio_authority?:{status:string;decision?:string|null;rank?:number|null;candidate_count?:number|null;final_portfolio_score?:number|null;optimizer_status?:string|null;selected_in_global_optimum?:boolean|null;optimality_proven?:boolean};
};
export type InstitutionalOptionWorkspace={
  opportunity:InstitutionalOptionOpportunitySummary&Record<string,any>;thesis:Record<string,any>|null;
  strategies:Record<string,any>[];comparison:Record<string,any>|null;contracts:Record<string,any>[];
  valuations:Record<string,any>[];execution_recommendation:Record<string,any>|null;
  management_snapshots:Record<string,any>[];decision_snapshot:Record<string,any>|null;audit:Record<string,any>[];
};

export type DynamicExitInstruction={instruction_id:string;assessment_id:string;position_id:string;action:string;quantity:number;status:string;payload:Record<string,any>;created_at:string};
