from sqlalchemy import JSON,Float,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from trading_ai.database.base import Base

class ExecutionIntelligenceSnapshotModel(Base):
    __tablename__='execution_intelligence_snapshots'
    execution_snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    execution_intent_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    execution_intent_version:Mapped[int]=mapped_column(Integer,nullable=False)
    trade_plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    symbol:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    decision:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    execution_confidence:Mapped[float]=mapped_column(Float,nullable=False)
    approved_reference_price:Mapped[float]=mapped_column(Float,nullable=False)
    fresh_executable_price:Mapped[float]=mapped_column(Float,nullable=False)
    governed_limit_price:Mapped[float]=mapped_column(Float,nullable=False)
    adverse_price_drift_pct:Mapped[float]=mapped_column(Float,nullable=False)
    quote_age_seconds:Mapped[float|None]=mapped_column(Float,nullable=True)
    fresh_max_loss:Mapped[float]=mapped_column(Float,nullable=False)
    risk_budget_amount:Mapped[float]=mapped_column(Float,nullable=False)
    validation_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    quotes_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    envelope_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    policy_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    evidence_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    created_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)

class ExecutionIntelligenceEventModel(Base):
    __tablename__='execution_intelligence_events'
    event_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    execution_snapshot_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    execution_intent_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    event_type:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    actor:Mapped[str]=mapped_column(String(128),nullable=False)
    reason:Mapped[str]=mapped_column(Text,nullable=False)
    payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    created_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)

class ExecutionOrderTelemetryModel(Base):
    __tablename__='execution_order_telemetry'
    execution_intent_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    trade_plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    execution_snapshot_id:Mapped[str|None]=mapped_column(String(128),index=True)
    aggregate_id:Mapped[str|None]=mapped_column(String(128),index=True)
    broker_order_id:Mapped[int|None]=mapped_column(Integer,index=True)
    symbol:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    state:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    approved_reference_price:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    fresh_midpoint_price:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    fresh_executable_price:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    submitted_limit_price:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    average_fill_price:Mapped[float|None]=mapped_column(Float)
    filled_quantity:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    remaining_quantity:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    commission_total:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    quote_age_seconds:Mapped[float|None]=mapped_column(Float)
    execution_confidence:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    market_drift_pct:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    execution_slippage_pct:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    realized_slippage_pct:Mapped[float|None]=mapped_column(Float)
    fill_rate_pct:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    execution_quality_score:Mapped[float]=mapped_column(Float,nullable=False,default=0,index=True)
    first_submitted_at:Mapped[str|None]=mapped_column(String(64),index=True)
    acknowledged_at:Mapped[str|None]=mapped_column(String(64))
    first_fill_at:Mapped[str|None]=mapped_column(String(64))
    filled_at:Mapped[str|None]=mapped_column(String(64),index=True)
    updated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    details_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)

class ExecutionFillEventModel(Base):
    __tablename__='execution_fill_events'
    fill_event_id:Mapped[str]=mapped_column(String(160),primary_key=True)
    execution_intent_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    aggregate_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    broker_execution_id:Mapped[str]=mapped_column(String(128),nullable=False,unique=True,index=True)
    broker_order_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True)
    symbol:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    side:Mapped[str]=mapped_column(String(16),nullable=False)
    quantity:Mapped[float]=mapped_column(Float,nullable=False)
    price:Mapped[float]=mapped_column(Float,nullable=False)
    commission:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    executed_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    payload_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)

class WorkingOrderAssessmentModel(Base):
    __tablename__='execution_working_order_assessments'
    assessment_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    execution_intent_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    execution_snapshot_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
    state:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    recommended_action:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    current_limit_price:Mapped[float]=mapped_column(Float,nullable=False)
    governed_limit_price:Mapped[float]=mapped_column(Float,nullable=False)
    filled_quantity:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    remaining_quantity:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    working_age_seconds:Mapped[float]=mapped_column(Float,nullable=False,default=0)
    evidence_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
    created_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)

class ExecutionLearningSampleModel(Base):
    __tablename__='execution_learning_samples'
    execution_intent_id:Mapped[str]=mapped_column(String(128),primary_key=True)
    symbol:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    outcome:Mapped[str]=mapped_column(String(32),nullable=False,index=True)
    execution_quality_score:Mapped[float]=mapped_column(Float,nullable=False,index=True)
    features_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    outcome_json:Mapped[dict]=mapped_column(JSON,nullable=False)
    created_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
    updated_at:Mapped[str]=mapped_column(String(64),nullable=False)
