"""Milestone 44 normalized market structure persistence.
Revision ID: m44_002
Revises: m44_001
"""
from alembic import op
import sqlalchemy as sa
revision='m44_002'; down_revision='m44_001'; branch_labels=None; depends_on=None

def upgrade():
    op.rename_table('institutional_market_structure_snapshot','institutional_market_structure_snapshot_legacy')
    op.create_table('dealer_position_snapshot',
        sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),primary_key=True),sa.Column('quote_date',sa.Date(),nullable=False,index=True),sa.Column('spot_price',sa.Float(),nullable=False),sa.Column('source_table',sa.String(128),nullable=False),sa.Column('dealer_sign_convention',sa.String(32),nullable=False),sa.Column('estimator_name',sa.String(96),nullable=False),sa.Column('estimator_version',sa.String(24),nullable=False),sa.Column('source_contract_count',sa.Integer(),nullable=False),sa.Column('executable_contract_count',sa.Integer(),nullable=False),sa.Column('quote_coverage_pct',sa.Float(),nullable=False),sa.Column('unsigned_gamma_exposure',sa.Float(),nullable=False),sa.Column('unsigned_delta_exposure',sa.Float(),nullable=False),sa.Column('net_gamma_exposure',sa.Float(),nullable=False),sa.Column('net_delta_exposure',sa.Float(),nullable=False),sa.Column('net_vanna_exposure',sa.Float(),nullable=False),sa.Column('net_charm_exposure',sa.Float(),nullable=False),sa.Column('gamma_regime',sa.String(32),nullable=False),sa.Column('gamma_flip',sa.Float()),sa.Column('gamma_flip_distance_pct',sa.Float()),sa.Column('gamma_flip_confidence',sa.Float(),nullable=False),sa.Column('primary_call_wall',sa.Float()),sa.Column('secondary_call_wall',sa.Float()),sa.Column('primary_put_wall',sa.Float()),sa.Column('secondary_put_wall',sa.Float()),sa.Column('magnet_strike',sa.Float()),sa.Column('expected_move',sa.Float()),sa.Column('expected_move_pct',sa.Float()),sa.Column('atm_iv',sa.Float()),sa.Column('iv_term_slope',sa.Float()),sa.Column('put_skew',sa.Float()),sa.Column('call_skew',sa.Float()),sa.Column('institutional_positioning_score',sa.Float(),nullable=False),sa.Column('positioning_label',sa.String(32),nullable=False),sa.Column('bull_probability',sa.Float(),nullable=False),sa.Column('bear_probability',sa.Float(),nullable=False),sa.Column('range_probability',sa.Float(),nullable=False),sa.Column('breakout_probability',sa.Float(),nullable=False),sa.Column('breakdown_probability',sa.Float(),nullable=False),sa.Column('volatility_expansion_probability',sa.Float(),nullable=False),sa.Column('volatility_compression_probability',sa.Float(),nullable=False),sa.Column('confidence',sa.String(16),nullable=False),sa.Column('confidence_score',sa.Float(),nullable=False),sa.Column('warnings_json',sa.Text(),nullable=False),sa.Column('assumptions_json',sa.Text(),nullable=False),sa.Column('provenance_json',sa.Text(),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
    op.create_table('dealer_strike_profile',sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),primary_key=True),sa.Column('expiry',sa.Date(),primary_key=True),sa.Column('strike',sa.Float(),primary_key=True),sa.Column('dte',sa.Integer(),nullable=False),*[sa.Column(n,sa.Float(),nullable=n in {'call_spread_pct','put_spread_pct'}) for n in ['call_open_interest','put_open_interest','call_volume','put_volume','call_gamma_exposure','put_gamma_exposure','net_gamma_exposure','call_delta_exposure','put_delta_exposure','net_delta_exposure','vanna_exposure','charm_exposure','call_spread_pct','put_spread_pct','liquidity_score','dealer_pressure_score','pin_score']],sa.Column('market_structure_eligible',sa.Boolean(),nullable=False),sa.Column('trade_eligible',sa.Boolean(),nullable=False))
    op.create_table('dealer_expiration_profile',sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),primary_key=True),sa.Column('expiry',sa.Date(),primary_key=True),sa.Column('dte',sa.Integer(),nullable=False),*[sa.Column(n,sa.Float(),nullable=n in {'atm_implied_volatility','expected_move'}) for n in ['call_open_interest','put_open_interest','net_gamma_exposure','net_delta_exposure','net_vanna_exposure','net_charm_exposure','atm_implied_volatility','expected_move','liquidity_score']])
    op.create_table('iv_surface_snapshot',sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),primary_key=True),sa.Column('expiry',sa.Date(),primary_key=True),sa.Column('strike',sa.Float(),primary_key=True),sa.Column('option_type',sa.String(8),primary_key=True),sa.Column('dte',sa.Integer(),nullable=False),sa.Column('moneyness',sa.Float(),nullable=False),sa.Column('delta',sa.Float()),sa.Column('implied_volatility',sa.Float(),nullable=False),sa.Column('bid',sa.Float(),nullable=False),sa.Column('ask',sa.Float(),nullable=False),sa.Column('mid',sa.Float(),nullable=False),sa.Column('spread_pct',sa.Float()))
def downgrade():
    for t in ('iv_surface_snapshot','dealer_expiration_profile','dealer_strike_profile','dealer_position_snapshot'): op.drop_table(t)
    op.rename_table('institutional_market_structure_snapshot_legacy','institutional_market_structure_snapshot')
