"""Milestone 46 market intelligence and institutional analytics.
Revision ID: m46_001
Revises: m45_001
"""
from alembic import op
import sqlalchemy as sa
revision='m46_001';down_revision='m45_001';branch_labels=None;depends_on=None

def audit_columns():
 return [sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False)]
def upgrade():
 op.create_table('sector_membership',sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('effective_from',sa.Date(),primary_key=True),sa.Column('company_name',sa.String(255),nullable=False),sa.Column('sector',sa.String(96),nullable=False,index=True),sa.Column('industry',sa.String(128)),sa.Column('sub_industry',sa.String(128)),sa.Column('sector_etf',sa.String(16)),sa.Column('classification_source',sa.String(255),nullable=False),sa.Column('effective_to',sa.Date()),sa.Column('is_active',sa.Boolean(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('last_verified_at',sa.DateTime(timezone=True),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('market_intelligence_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('universe_name',sa.String(64),nullable=False),sa.Column('source_snapshot_timestamp',sa.DateTime(timezone=True),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('calculation_version',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
 op.create_table('symbol_return_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('return_1d',sa.Float()),sa.Column('return_5d',sa.Float()),sa.Column('return_20d',sa.Float()),sa.Column('realized_volatility_20d',sa.Float()),sa.Column('beta_60d',sa.Float()),sa.Column('sector',sa.String(96)),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('correlation_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('universe_name',sa.String(64),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('lookback_days',sa.Integer(),nullable=False),sa.Column('average_pairwise_correlation',sa.Float(),nullable=False),sa.Column('median_pairwise_correlation',sa.Float(),nullable=False),sa.Column('dispersion',sa.Float(),nullable=False),sa.Column('correlation_regime',sa.String(32),nullable=False),sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('correlation_pair_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('symbol_a',sa.String(16),primary_key=True),sa.Column('symbol_b',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('lookback_days',sa.Integer(),nullable=False),sa.Column('correlation',sa.Float(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False))
 op.create_table('sector_breadth_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('sector',sa.String(96),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('sector_etf',sa.String(16)),sa.Column('constituent_count',sa.Integer(),nullable=False),sa.Column('breadth_score',sa.Float(),nullable=False),sa.Column('momentum_score',sa.Float(),nullable=False),sa.Column('rotation_label',sa.String(24),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('market_sentiment_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('overall_sentiment_score',sa.Float(),nullable=False),sa.Column('risk_appetite_score',sa.Float(),nullable=False),sa.Column('fear_score',sa.Float(),nullable=False),sa.Column('sentiment_label',sa.String(24),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('sentiment_component_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('component_name',sa.String(64),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('score',sa.Float(),nullable=False),sa.Column('weight',sa.Float(),nullable=False),sa.Column('contribution',sa.Float(),nullable=False),sa.Column('direction',sa.String(16),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 for name in ['market_internal_snapshot','market_volatility_snapshot','market_liquidity_snapshot','market_risk_snapshot']:
  op.create_table(name,sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('score',sa.Float(),nullable=False),sa.Column('regime',sa.String(32),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('dealer_position_change_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('symbol',sa.String(16),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('positioning_score',sa.Float(),nullable=False),sa.Column('dealer_conviction_score',sa.Float(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
 op.create_table('market_opportunity_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('opportunity_rank',sa.Integer(),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False,index=True),sa.Column('opportunity_type',sa.String(48),nullable=False),sa.Column('instrument',sa.String(32),nullable=False),sa.Column('direction',sa.String(16),nullable=False),sa.Column('strategy_family',sa.String(48),nullable=False),sa.Column('score',sa.Float(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))

def downgrade():
 for name in ['market_opportunity_snapshot','dealer_position_change_snapshot','market_risk_snapshot','market_liquidity_snapshot','market_volatility_snapshot','market_internal_snapshot','sentiment_component_snapshot','market_sentiment_snapshot','sector_breadth_snapshot','correlation_pair_snapshot','correlation_snapshot','symbol_return_snapshot','market_intelligence_snapshot','sector_membership']:
  op.drop_table(name)
