"""Milestone 46 Polygon authoritative data closure.

Revision ID: m46_002
Revises: m46_001
"""
from alembic import op
import sqlalchemy as sa
revision='m46_002'
down_revision='m46_001'
branch_labels=None
depends_on=None

def upgrade():
    op.create_table('option_snapshot_run',
        sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),
        sa.Column('snapshot_id',sa.String(96),nullable=False),sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),nullable=False),sa.Column('as_of_date',sa.Date(),nullable=False),
        sa.Column('provider',sa.String(32),nullable=False,server_default='POLYGON'),sa.Column('capture_status',sa.String(24),nullable=False),sa.Column('is_partial',sa.Boolean(),nullable=False,server_default=sa.false()),
        sa.Column('completeness_score',sa.Float(),nullable=False,server_default='0'),sa.Column('symbols_requested',sa.Integer(),nullable=False,server_default='0'),sa.Column('symbols_succeeded',sa.Integer(),nullable=False,server_default='0'),sa.Column('symbols_failed',sa.Integer(),nullable=False,server_default='0'),sa.Column('contracts_received',sa.Integer(),nullable=False,server_default='0'),sa.Column('contracts_persisted',sa.Integer(),nullable=False,server_default='0'),
        sa.Column('warnings_json',sa.Text(),nullable=False,server_default='[]'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('provider','snapshot_id',name='uq_option_snapshot_run_provider_snapshot'))
    op.create_index('ix_option_snapshot_run_timestamp','option_snapshot_run',['snapshot_timestamp'])
    op.create_table('option_contract_snapshot',
        sa.Column('id',sa.BigInteger(),primary_key=True,autoincrement=True),sa.Column('snapshot_run_id',sa.BigInteger(),sa.ForeignKey('option_snapshot_run.id',ondelete='CASCADE'),nullable=False),
        sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),nullable=False),sa.Column('underlying_symbol',sa.String(24),nullable=False),sa.Column('option_symbol',sa.String(64),nullable=False),sa.Column('expiry',sa.Date(),nullable=False),sa.Column('option_type',sa.String(8),nullable=False),sa.Column('strike',sa.Float(),nullable=False),
        sa.Column('bid',sa.Float()),sa.Column('ask',sa.Float()),sa.Column('last',sa.Float()),sa.Column('mark',sa.Float()),sa.Column('volume',sa.BigInteger()),sa.Column('open_interest',sa.BigInteger()),sa.Column('implied_volatility',sa.Float()),sa.Column('delta',sa.Float()),sa.Column('gamma',sa.Float()),sa.Column('theta',sa.Float()),sa.Column('vega',sa.Float()),sa.Column('vanna',sa.Float()),sa.Column('charm',sa.Float()),sa.Column('underlying_price',sa.Float()),sa.Column('quote_timestamp',sa.DateTime(timezone=True)),sa.Column('trade_timestamp',sa.DateTime(timezone=True)),sa.Column('quote_quality',sa.String(24),nullable=False,server_default='UNKNOWN'),sa.Column('provider',sa.String(32),nullable=False,server_default='POLYGON'),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.UniqueConstraint('snapshot_run_id','option_symbol',name='uq_option_contract_snapshot_run_symbol'))
    op.create_index('ix_option_contract_snapshot_lookup','option_contract_snapshot',['underlying_symbol','snapshot_timestamp'])
    op.create_table('underlying_volatility_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('underlying_symbol',sa.String(24),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False),sa.Column('atm_iv_30d',sa.Float()),sa.Column('realized_vol_20d',sa.Float()),sa.Column('iv_rank_252d',sa.Float()),sa.Column('iv_percentile_252d',sa.Float()),sa.Column('volatility_risk_premium',sa.Float()),sa.Column('put_skew_25d',sa.Float()),sa.Column('term_structure_slope',sa.Float()),sa.Column('strategy_fit',sa.String(40),nullable=False),sa.Column('observation_count',sa.Integer(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(32),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
    op.create_table('market_trade_event',sa.Column('id',sa.BigInteger(),primary_key=True),sa.Column('provider',sa.String(32),nullable=False),sa.Column('event_timestamp',sa.DateTime(timezone=True),nullable=False),sa.Column('sequence_number',sa.BigInteger(),nullable=False),sa.Column('symbol',sa.String(64),nullable=False),sa.Column('asset_type',sa.String(16),nullable=False),sa.Column('price',sa.Float(),nullable=False),sa.Column('size',sa.Float(),nullable=False),sa.Column('exchange',sa.String(16)),sa.Column('conditions_json',sa.Text(),nullable=False,server_default='[]'),sa.UniqueConstraint('provider','symbol','event_timestamp','sequence_number',name='uq_market_trade_event'))
    op.create_index('ix_market_trade_event_symbol_ts','market_trade_event',['symbol','event_timestamp'])
    op.create_table('market_quote_event',sa.Column('id',sa.BigInteger(),primary_key=True),sa.Column('provider',sa.String(32),nullable=False),sa.Column('event_timestamp',sa.DateTime(timezone=True),nullable=False),sa.Column('sequence_number',sa.BigInteger(),nullable=False),sa.Column('symbol',sa.String(64),nullable=False),sa.Column('asset_type',sa.String(16),nullable=False),sa.Column('bid_price',sa.Float()),sa.Column('bid_size',sa.Float()),sa.Column('ask_price',sa.Float()),sa.Column('ask_size',sa.Float()),sa.Column('bid_exchange',sa.String(16)),sa.Column('ask_exchange',sa.String(16)),sa.UniqueConstraint('provider','symbol','event_timestamp','sequence_number',name='uq_market_quote_event'))
    op.create_index('ix_market_quote_event_symbol_ts','market_quote_event',['symbol','event_timestamp'])
    op.create_table('microstructure_liquidity_snapshot',sa.Column('snapshot_timestamp',sa.DateTime(timezone=True),primary_key=True),sa.Column('symbol',sa.String(64),primary_key=True),sa.Column('as_of_date',sa.Date(),nullable=False),sa.Column('executable_quote_pct',sa.Float()),sa.Column('median_relative_spread_pct',sa.Float()),sa.Column('average_trade_size',sa.Float()),sa.Column('liquidity_score',sa.Float(),nullable=False),sa.Column('liquidity_regime',sa.String(24),nullable=False),sa.Column('depth_available',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('provenance',sa.String(48),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False))
    op.create_table('institutional_market_context_evaluation',sa.Column('id',sa.BigInteger(),primary_key=True),sa.Column('decision_id',sa.String(96),nullable=False,index=True),sa.Column('symbol',sa.String(24),nullable=False),sa.Column('snapshot_timestamp',sa.DateTime(timezone=True)),sa.Column('policy_version',sa.String(32),nullable=False),sa.Column('outcome',sa.String(32),nullable=False),sa.Column('allowed',sa.Boolean(),nullable=False),sa.Column('total_adjustment',sa.Float(),nullable=False),sa.Column('confidence',sa.Float(),nullable=False),sa.Column('reasons_json',sa.Text(),nullable=False),sa.Column('conflicts_json',sa.Text(),nullable=False),sa.Column('payload_json',sa.Text(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))

def downgrade():
    for name in ['institutional_market_context_evaluation','microstructure_liquidity_snapshot','market_quote_event','market_trade_event','underlying_volatility_snapshot','option_contract_snapshot','option_snapshot_run']:
        op.drop_table(name)
