"""Milestone 65 performance command center and outcome learning
Revision ID: m65_001
Revises: m64_003
"""
from alembic import op
import sqlalchemy as sa
revision='m65_001';down_revision='m64_003';branch_labels=None;depends_on=None

def upgrade():
 op.create_table('performance_trade_outcomes',sa.Column('outcome_id',sa.String(128),primary_key=True),sa.Column('position_id',sa.String(128),nullable=False),sa.Column('position_version',sa.Integer(),nullable=False),sa.Column('portfolio_id',sa.String(128),nullable=False),sa.Column('opportunity_id',sa.String(128),nullable=False),sa.Column('decision_snapshot_id',sa.String(128)),sa.Column('portfolio_decision_id',sa.String(128)),sa.Column('strategy',sa.String(64),nullable=False),sa.Column('market_regime',sa.String(64),nullable=False),sa.Column('outcome',sa.String(16),nullable=False),sa.Column('predicted_probability',sa.Float(),nullable=False),sa.Column('expected_value',sa.Float(),nullable=False),sa.Column('realized_pnl',sa.Float(),nullable=False),sa.Column('realized_return_pct',sa.Float(),nullable=False),sa.Column('maximum_drawdown_pct',sa.Float(),nullable=False),sa.Column('holding_days',sa.Float(),nullable=False),sa.Column('opened_at',sa.String(64),nullable=False),sa.Column('closed_at',sa.String(64)),sa.Column('reconstructed_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.UniqueConstraint('position_id','position_version',name='uq_m65_outcome_position_version'))
 op.create_table('performance_attribution_snapshots',sa.Column('attribution_snapshot_id',sa.String(128),primary_key=True),sa.Column('portfolio_id',sa.String(128),nullable=False),sa.Column('generated_at',sa.String(64),nullable=False),sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False))
 op.create_table('performance_calibration_snapshots',sa.Column('calibration_snapshot_id',sa.String(128),primary_key=True),sa.Column('portfolio_id',sa.String(128),nullable=False),sa.Column('scope',sa.String(64),nullable=False),sa.Column('scope_value',sa.String(128),nullable=False),sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('brier_score',sa.Float(),nullable=False),sa.Column('log_loss',sa.Float(),nullable=False),sa.Column('expected_calibration_error',sa.Float(),nullable=False),sa.Column('generated_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False))
 op.create_table('performance_counterfactual_outcomes',sa.Column('counterfactual_id',sa.String(128),primary_key=True),sa.Column('portfolio_id',sa.String(128),nullable=False),sa.Column('opportunity_id',sa.String(128),nullable=False),sa.Column('decision_state_hash',sa.String(128),nullable=False),sa.Column('decision',sa.String(32),nullable=False),sa.Column('selected',sa.Integer(),nullable=False),sa.Column('predicted_probability',sa.Float(),nullable=False),sa.Column('observed_return_pct',sa.Float()),sa.Column('evaluation_status',sa.String(32),nullable=False),sa.Column('evaluated_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.UniqueConstraint('portfolio_id','opportunity_id','decision_state_hash',name='uq_m65_counterfactual_decision'))
 op.create_table('performance_learning_publications',sa.Column('publication_id',sa.String(128),primary_key=True),sa.Column('publication_name',sa.String(128),nullable=False),sa.Column('portfolio_id',sa.String(128),nullable=False),sa.Column('report_id',sa.String(128),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('sample_size',sa.Integer(),nullable=False),sa.Column('published_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False))

def downgrade():
 for t in ('performance_learning_publications','performance_counterfactual_outcomes','performance_calibration_snapshots','performance_attribution_snapshots','performance_trade_outcomes'):op.drop_table(t)
