"""Milestone 66 production operations and reliability

Revision ID: m66_001
Revises: m65_001
"""
from alembic import op
import sqlalchemy as sa
revision='m66_001';down_revision='m65_001';branch_labels=None;depends_on=None

def upgrade():
 op.create_table('production_ops_services',sa.Column('service_id',sa.String(96),primary_key=True),sa.Column('name',sa.String(160),nullable=False),sa.Column('domain',sa.String(64),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('critical',sa.Boolean(),nullable=False),sa.Column('heartbeat_at',sa.String(64)),sa.Column('last_success_at',sa.String(64)),sa.Column('last_failure_at',sa.String(64)),sa.Column('next_run_at',sa.String(64)),sa.Column('latency_ms',sa.Float()),sa.Column('retry_count',sa.Integer(),nullable=False),sa.Column('dependencies_json',sa.JSON(),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('updated_at',sa.String(64),nullable=False))
 op.create_table('production_ops_workflow_runs',sa.Column('run_id',sa.String(128),primary_key=True),sa.Column('workflow_name',sa.String(128),nullable=False),sa.Column('mode',sa.String(32),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('started_at',sa.String(64),nullable=False),sa.Column('finished_at',sa.String(64)),sa.Column('actor',sa.String(128),nullable=False),sa.Column('current_stage',sa.String(128)),sa.Column('stage_results_json',sa.JSON(),nullable=False),sa.Column('error',sa.Text()),sa.Column('metadata_json',sa.JSON(),nullable=False))
 op.create_table('production_ops_publication_freshness',sa.Column('freshness_id',sa.String(128),primary_key=True),sa.Column('publication_name',sa.String(128),nullable=False),sa.Column('source_id',sa.String(160),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('published_at',sa.String(64)),sa.Column('age_seconds',sa.Float()),sa.Column('maximum_age_seconds',sa.Integer(),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('lineage_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.String(64),nullable=False),sa.UniqueConstraint('publication_name','source_id',name='uq_m66_publication_source'))
 op.create_table('production_ops_readiness_publications',sa.Column('publication_id',sa.String(128),primary_key=True),sa.Column('publication_name',sa.String(128),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('scanner_ready',sa.Boolean(),nullable=False),sa.Column('decision_ready',sa.Boolean(),nullable=False),sa.Column('execution_ready',sa.Boolean(),nullable=False),sa.Column('management_ready',sa.Boolean(),nullable=False),sa.Column('portfolio_ready',sa.Boolean(),nullable=False),sa.Column('learning_ready',sa.Boolean(),nullable=False),sa.Column('platform_ready',sa.Boolean(),nullable=False),sa.Column('published_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False))
 op.create_table('production_ops_alerts',sa.Column('alert_id',sa.String(128),primary_key=True),sa.Column('fingerprint',sa.String(160),nullable=False),sa.Column('severity',sa.String(24),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('category',sa.String(64),nullable=False),sa.Column('title',sa.String(256),nullable=False),sa.Column('message',sa.Text(),nullable=False),sa.Column('owner',sa.String(128),nullable=False),sa.Column('recommended_action',sa.Text(),nullable=False),sa.Column('created_at',sa.String(64),nullable=False),sa.Column('updated_at',sa.String(64),nullable=False),sa.Column('acknowledged_at',sa.String(64)),sa.Column('acknowledged_by',sa.String(128)),sa.Column('payload_json',sa.JSON(),nullable=False))
 op.create_table('production_ops_recovery_actions',sa.Column('recovery_id',sa.String(128),primary_key=True),sa.Column('action_type',sa.String(64),nullable=False),sa.Column('target_type',sa.String(64),nullable=False),sa.Column('target_id',sa.String(160),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('actor',sa.String(128),nullable=False),sa.Column('reason',sa.Text(),nullable=False),sa.Column('started_at',sa.String(64),nullable=False),sa.Column('finished_at',sa.String(64)),sa.Column('result_json',sa.JSON(),nullable=False))
 op.create_table('production_ops_locks',sa.Column('lock_name',sa.String(160),primary_key=True),sa.Column('owner_id',sa.String(160),nullable=False),sa.Column('acquired_at',sa.String(64),nullable=False),sa.Column('heartbeat_at',sa.String(64),nullable=False),sa.Column('expires_at',sa.String(64),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False))
 op.create_table('production_ops_audit_events',sa.Column('event_id',sa.String(128),primary_key=True),sa.Column('entity_type',sa.String(64),nullable=False),sa.Column('entity_id',sa.String(160),nullable=False),sa.Column('event_type',sa.String(96),nullable=False),sa.Column('actor',sa.String(128),nullable=False),sa.Column('occurred_at',sa.String(64),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False))
def downgrade():
 for t in ['production_ops_audit_events','production_ops_locks','production_ops_recovery_actions','production_ops_alerts','production_ops_readiness_publications','production_ops_publication_freshness','production_ops_workflow_runs','production_ops_services']:op.drop_table(t)
