"""M70 execution intelligence completion: telemetry, fills, working-order assessments, learning hooks.
Revision ID: m70_003
Revises: m70_002
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='m70_003';down_revision='m70_002';branch_labels=None;depends_on=None

def upgrade():
    op.create_table('execution_order_telemetry',
      sa.Column('execution_intent_id',sa.String(128),primary_key=True),sa.Column('trade_plan_id',sa.String(128),nullable=False),sa.Column('execution_snapshot_id',sa.String(128)),sa.Column('aggregate_id',sa.String(128)),sa.Column('broker_order_id',sa.Integer()),sa.Column('symbol',sa.String(32),nullable=False),sa.Column('strategy',sa.String(64),nullable=False),sa.Column('state',sa.String(32),nullable=False),sa.Column('approved_reference_price',sa.Float(),nullable=False,server_default='0'),sa.Column('fresh_midpoint_price',sa.Float(),nullable=False,server_default='0'),sa.Column('fresh_executable_price',sa.Float(),nullable=False,server_default='0'),sa.Column('submitted_limit_price',sa.Float(),nullable=False,server_default='0'),sa.Column('average_fill_price',sa.Float()),sa.Column('filled_quantity',sa.Float(),nullable=False,server_default='0'),sa.Column('remaining_quantity',sa.Float(),nullable=False,server_default='0'),sa.Column('commission_total',sa.Float(),nullable=False,server_default='0'),sa.Column('quote_age_seconds',sa.Float()),sa.Column('execution_confidence',sa.Float(),nullable=False,server_default='0'),sa.Column('market_drift_pct',sa.Float(),nullable=False,server_default='0'),sa.Column('execution_slippage_pct',sa.Float(),nullable=False,server_default='0'),sa.Column('realized_slippage_pct',sa.Float()),sa.Column('fill_rate_pct',sa.Float(),nullable=False,server_default='0'),sa.Column('execution_quality_score',sa.Float(),nullable=False,server_default='0'),sa.Column('first_submitted_at',sa.String(64)),sa.Column('acknowledged_at',sa.String(64)),sa.Column('first_fill_at',sa.String(64)),sa.Column('filled_at',sa.String(64)),sa.Column('updated_at',sa.String(64),nullable=False),sa.Column('details_json',postgresql.JSONB(astext_type=sa.Text()),nullable=False,server_default=sa.text("'{}'::jsonb")))
    op.create_index('ix_m70_telemetry_state','execution_order_telemetry',['state']);op.create_index('ix_m70_telemetry_symbol','execution_order_telemetry',['symbol']);op.create_index('ix_m70_telemetry_quality','execution_order_telemetry',['execution_quality_score']);op.create_index('ix_m70_telemetry_updated','execution_order_telemetry',['updated_at'])
    op.create_table('execution_fill_events',sa.Column('fill_event_id',sa.String(160),primary_key=True),sa.Column('execution_intent_id',sa.String(128),nullable=False),sa.Column('aggregate_id',sa.String(128),nullable=False),sa.Column('broker_execution_id',sa.String(128),nullable=False,unique=True),sa.Column('broker_order_id',sa.Integer(),nullable=False),sa.Column('symbol',sa.String(64),nullable=False),sa.Column('side',sa.String(16),nullable=False),sa.Column('quantity',sa.Float(),nullable=False),sa.Column('price',sa.Float(),nullable=False),sa.Column('commission',sa.Float(),nullable=False,server_default='0'),sa.Column('executed_at',sa.String(64),nullable=False),sa.Column('payload_json',postgresql.JSONB(astext_type=sa.Text()),nullable=False,server_default=sa.text("'{}'::jsonb")))
    op.create_index('ix_m70_fills_intent','execution_fill_events',['execution_intent_id','executed_at']);op.create_index('ix_m70_fills_symbol','execution_fill_events',['symbol'])
    op.create_table('execution_working_order_assessments',sa.Column('assessment_id',sa.String(128),primary_key=True),sa.Column('execution_intent_id',sa.String(128),nullable=False),sa.Column('execution_snapshot_id',sa.String(128),nullable=False),sa.Column('state',sa.String(32),nullable=False),sa.Column('recommended_action',sa.String(32),nullable=False),sa.Column('current_limit_price',sa.Float(),nullable=False),sa.Column('governed_limit_price',sa.Float(),nullable=False),sa.Column('filled_quantity',sa.Float(),nullable=False,server_default='0'),sa.Column('remaining_quantity',sa.Float(),nullable=False,server_default='0'),sa.Column('working_age_seconds',sa.Float(),nullable=False,server_default='0'),sa.Column('evidence_json',postgresql.JSONB(astext_type=sa.Text()),nullable=False,server_default=sa.text("'{}'::jsonb")),sa.Column('created_at',sa.String(64),nullable=False))
    op.create_index('ix_m70_working_intent','execution_working_order_assessments',['execution_intent_id','created_at']);op.create_index('ix_m70_working_action','execution_working_order_assessments',['recommended_action'])
    op.create_table('execution_learning_samples',sa.Column('execution_intent_id',sa.String(128),primary_key=True),sa.Column('symbol',sa.String(32),nullable=False),sa.Column('strategy',sa.String(64),nullable=False),sa.Column('outcome',sa.String(32),nullable=False),sa.Column('execution_quality_score',sa.Float(),nullable=False),sa.Column('features_json',postgresql.JSONB(astext_type=sa.Text()),nullable=False),sa.Column('outcome_json',postgresql.JSONB(astext_type=sa.Text()),nullable=False),sa.Column('created_at',sa.String(64),nullable=False),sa.Column('updated_at',sa.String(64),nullable=False))
    op.create_index('ix_m70_learning_outcome','execution_learning_samples',['outcome']);op.create_index('ix_m70_learning_strategy','execution_learning_samples',['strategy']);op.create_index('ix_m70_learning_quality','execution_learning_samples',['execution_quality_score'])

def downgrade():
    for idx,table in [('ix_m70_learning_quality','execution_learning_samples'),('ix_m70_learning_strategy','execution_learning_samples'),('ix_m70_learning_outcome','execution_learning_samples')]:op.drop_index(idx,table_name=table)
    op.drop_table('execution_learning_samples')
    op.drop_index('ix_m70_working_action',table_name='execution_working_order_assessments');op.drop_index('ix_m70_working_intent',table_name='execution_working_order_assessments');op.drop_table('execution_working_order_assessments')
    op.drop_index('ix_m70_fills_symbol',table_name='execution_fill_events');op.drop_index('ix_m70_fills_intent',table_name='execution_fill_events');op.drop_table('execution_fill_events')
    for idx in ['ix_m70_telemetry_updated','ix_m70_telemetry_quality','ix_m70_telemetry_symbol','ix_m70_telemetry_state']:op.drop_index(idx,table_name='execution_order_telemetry')
    op.drop_table('execution_order_telemetry')
