"""M77.1 isolated historical underlying replay authority.
Revision ID: m77_002
Revises: m68_004
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='m77_002'; down_revision='m68_004'; branch_labels=None; depends_on=None
def upgrade():
 op.create_table('historical_underlying_replay_authority',sa.Column('symbol',sa.String(32),primary_key=True),sa.Column('disposition',sa.String(64),nullable=False),sa.Column('continuity_start',sa.Date,nullable=False),sa.Column('eligible_from',sa.Date),sa.Column('last_date',sa.Date,nullable=False),sa.Column('valid_observation_count',sa.Integer,nullable=False),sa.Column('identity_break_count',sa.Integer,nullable=False),sa.Column('invalid_session_count',sa.Integer,nullable=False),sa.Column('authority_version',sa.String(96),nullable=False),sa.Column('evidence_json',postgresql.JSONB,nullable=False),sa.Column('materialized_at',sa.DateTime(timezone=True),nullable=False))
 op.create_index('ix_m77_1_authority_disposition','historical_underlying_replay_authority',['disposition'])
 op.create_table('historical_underlying_replay_run',sa.Column('replay_run_id',sa.String(128),primary_key=True),sa.Column('replay_mode',sa.String(64),nullable=False),sa.Column('champion_mode',sa.String(96),nullable=False),sa.Column('start_date',sa.Date,nullable=False),sa.Column('end_date',sa.Date,nullable=False),sa.Column('cadence',sa.String(16),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('authority_version',sa.String(96),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('prediction_count',sa.Integer,nullable=False,server_default='0'),sa.Column('failure_count',sa.Integer,nullable=False,server_default='0'),sa.Column('metadata_json',postgresql.JSONB,nullable=False))
 op.create_table('historical_underlying_replay_prediction',sa.Column('prediction_id',sa.String(160),primary_key=True),sa.Column('replay_run_id',sa.String(128),sa.ForeignKey('historical_underlying_replay_run.replay_run_id',ondelete='CASCADE'),nullable=False),sa.Column('symbol',sa.String(32),nullable=False),sa.Column('as_of',sa.Date,nullable=False),sa.Column('direction',sa.String(32),nullable=False),sa.Column('primary_category',sa.String(64)),sa.Column('overall_score',sa.Float,nullable=False),sa.Column('confidence',sa.Float,nullable=False),sa.Column('state_hash',sa.String(64),nullable=False),sa.Column('profile_json',postgresql.JSONB,nullable=False),sa.Column('lineage_json',postgresql.JSONB,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('replay_run_id','symbol','as_of',name='uq_m77_1_replay_symbol_asof'))
 op.create_index('ix_m77_1_pred_run','historical_underlying_replay_prediction',['replay_run_id']); op.create_index('ix_m77_1_pred_symbol_asof','historical_underlying_replay_prediction',['symbol','as_of'])
 op.create_table('historical_underlying_replay_outcome',sa.Column('prediction_id',sa.String(160),sa.ForeignKey('historical_underlying_replay_prediction.prediction_id',ondelete='CASCADE'),primary_key=True),sa.Column('replay_run_id',sa.String(128),nullable=False),sa.Column('symbol',sa.String(32),nullable=False),sa.Column('as_of',sa.Date,nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('entry_triggered',sa.Boolean,nullable=False),sa.Column('ambiguous_same_bar',sa.Boolean,nullable=False),sa.Column('mfe_pct',sa.Float),sa.Column('mae_pct',sa.Float),sa.Column('return_5d_pct',sa.Float),sa.Column('return_10d_pct',sa.Float),sa.Column('return_20d_pct',sa.Float),sa.Column('return_40d_pct',sa.Float),sa.Column('return_60d_pct',sa.Float),sa.Column('outcome_json',postgresql.JSONB,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
 op.create_index('ix_m77_1_outcome_run','historical_underlying_replay_outcome',['replay_run_id'])
 op.create_table('historical_underlying_replay_failure',sa.Column('id',sa.BigInteger,primary_key=True,autoincrement=True),sa.Column('replay_run_id',sa.String(128),nullable=False),sa.Column('symbol',sa.String(32),nullable=False),sa.Column('as_of',sa.Date,nullable=False),sa.Column('error_type',sa.String(128),nullable=False),sa.Column('error_message',sa.Text,nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
def downgrade():
 op.drop_table('historical_underlying_replay_failure'); op.drop_table('historical_underlying_replay_outcome'); op.drop_table('historical_underlying_replay_prediction'); op.drop_table('historical_underlying_replay_run'); op.drop_table('historical_underlying_replay_authority')
