from sqlalchemy import JSON,Float,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from trading_ai.database.base import Base
class ManagedPositionModel(Base):
 __tablename__='managed_positions'
 __table_args__=(UniqueConstraint('portfolio_id','trade_plan_id',name='uq_m57_position_trade_plan'),)
 position_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);trade_plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);opportunity_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);intelligence_id:Mapped[str|None]=mapped_column(String(128));execution_id:Mapped[str|None]=mapped_column(String(128));symbol:Mapped[str]=mapped_column(String(32),nullable=False,index=True);strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True);direction:Mapped[str]=mapped_column(String(16),nullable=False);state:Mapped[str]=mapped_column(String(32),nullable=False,index=True);version:Mapped[int]=mapped_column(Integer,nullable=False,default=1);opened_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);closed_at:Mapped[str|None]=mapped_column(String(64));entry_value:Mapped[float]=mapped_column(Float,nullable=False);realized_pnl:Mapped[float]=mapped_column(Float,nullable=False,default=0);mark_json:Mapped[dict]=mapped_column(JSON,nullable=False);health_json:Mapped[dict]=mapped_column(JSON,nullable=False);decision_json:Mapped[dict]=mapped_column(JSON,nullable=False);metadata_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[str]=mapped_column(String(64),nullable=False);updated_at:Mapped[str]=mapped_column(String(64),nullable=False)
class PositionHealthSnapshotModel(Base):
 __tablename__='managed_position_health_snapshots'
 health_snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);position_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);position_version:Mapped[int]=mapped_column(Integer,nullable=False);snapshot_timestamp:Mapped[str]=mapped_column(String(64),nullable=False,index=True);health_score:Mapped[float]=mapped_column(Float,nullable=False);direction:Mapped[str]=mapped_column(String(32),nullable=False);confidence:Mapped[float]=mapped_column(Float,nullable=False);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)
class PortfolioSnapshotModel(Base):
 __tablename__='portfolio_intelligence_snapshots'
 snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);snapshot_timestamp:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False);generated_by:Mapped[str]=mapped_column(String(128),nullable=False)
class PositionEventModel(Base):
 __tablename__='managed_position_events'
 event_id:Mapped[str]=mapped_column(String(128),primary_key=True);position_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);position_version:Mapped[int]=mapped_column(Integer,nullable=False);event_type:Mapped[str]=mapped_column(String(64),nullable=False,index=True);actor:Mapped[str]=mapped_column(String(128),nullable=False);reason:Mapped[str]=mapped_column(Text,nullable=False);event_timestamp:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict)
class PositionAttributionModel(Base):
 __tablename__='position_attribution_reports'
 attribution_id:Mapped[str]=mapped_column(String(128),primary_key=True);position_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);generated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False);generated_by:Mapped[str]=mapped_column(String(128),nullable=False)
