"""Milestone 50 IBKR paper order routing.

Revision ID: m50_002
Revises: m50_001
"""
from alembic import op
import sqlalchemy as sa
revision='m50_002'; down_revision='m50_001'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('broker_order_controls',sa.Column('portfolio_id',sa.String(64),primary_key=True),sa.Column('paper_order_submission_enabled',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('activation_token_hash',sa.String(128),nullable=False,server_default=''),sa.Column('activated_at',sa.String(64)),sa.Column('activated_by',sa.String(128),nullable=False,server_default=''),sa.Column('disabled_at',sa.String(64)),sa.Column('disable_reason',sa.Text(),nullable=False,server_default=''),sa.Column('version',sa.Integer(),nullable=False,server_default='1'),sa.Column('updated_at',sa.String(64),nullable=False),sa.Column('metadata_json',sa.JSON(),nullable=False,server_default=sa.text("'{}'::json")))
    op.create_table('broker_orders',sa.Column('broker_order_record_id',sa.String(160),primary_key=True),sa.Column('binding_id',sa.String(128),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('aggregate_id',sa.String(128),nullable=False),sa.Column('client_order_id',sa.String(128),nullable=False),sa.Column('broker_account_id',sa.String(64),nullable=False),sa.Column('broker_order_id',sa.Integer(),nullable=False),sa.Column('permanent_id',sa.Integer(),nullable=False,server_default='0'),sa.Column('api_client_id',sa.Integer(),nullable=False),sa.Column('symbol',sa.String(64),nullable=False),sa.Column('security_type',sa.String(16),nullable=False),sa.Column('side',sa.String(16),nullable=False),sa.Column('quantity',sa.Float(),nullable=False),sa.Column('order_type',sa.String(16),nullable=False),sa.Column('time_in_force',sa.String(16),nullable=False),sa.Column('limit_price',sa.Float()),sa.Column('stop_price',sa.Float()),sa.Column('status',sa.String(32),nullable=False),sa.Column('filled_quantity',sa.Float(),nullable=False,server_default='0'),sa.Column('remaining_quantity',sa.Float(),nullable=False),sa.Column('average_fill_price',sa.Float(),nullable=False,server_default='0'),sa.Column('submitted_at',sa.String(64),nullable=False),sa.Column('updated_at',sa.String(64),nullable=False),sa.Column('last_error',sa.Text(),nullable=False,server_default=''),sa.Column('raw_json',sa.JSON(),nullable=False,server_default=sa.text("'{}'::json")),sa.UniqueConstraint('binding_id','aggregate_id',name='uq_broker_order_binding_aggregate'),sa.UniqueConstraint('binding_id','broker_order_id',name='uq_broker_order_binding_order_id'))
    op.create_table('broker_executions',sa.Column('execution_id',sa.String(128),primary_key=True),sa.Column('broker_order_record_id',sa.String(160),nullable=False),sa.Column('binding_id',sa.String(128),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('aggregate_id',sa.String(128),nullable=False),sa.Column('broker_account_id',sa.String(64),nullable=False),sa.Column('broker_order_id',sa.Integer(),nullable=False),sa.Column('permanent_id',sa.Integer(),nullable=False,server_default='0'),sa.Column('contract_id',sa.Integer(),nullable=False,server_default='0'),sa.Column('symbol',sa.String(64),nullable=False),sa.Column('security_type',sa.String(16),nullable=False),sa.Column('side',sa.String(16),nullable=False),sa.Column('quantity',sa.Float(),nullable=False),sa.Column('price',sa.Float(),nullable=False),sa.Column('commission',sa.Float(),nullable=False,server_default='0'),sa.Column('currency',sa.String(8),nullable=False,server_default='USD'),sa.Column('exchange',sa.String(32),nullable=False,server_default=''),sa.Column('executed_at',sa.String(64),nullable=False),sa.Column('imported_at',sa.String(64),nullable=False),sa.Column('settled',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('raw_json',sa.JSON(),nullable=False,server_default=sa.text("'{}'::json")))
    for table,cols in {'broker_orders':['binding_id','portfolio_id','aggregate_id','client_order_id','broker_account_id','broker_order_id','permanent_id','symbol','status'],'broker_executions':['broker_order_record_id','binding_id','portfolio_id','aggregate_id','broker_account_id','broker_order_id','permanent_id','contract_id','symbol','executed_at','settled']}.items():
        for col in cols: op.create_index(f'ix_{table}_{col}',table,[col])

def downgrade():
    op.drop_table('broker_executions'); op.drop_table('broker_orders'); op.drop_table('broker_order_controls')
