import { useEffect, useMemo, useState } from 'react';
import { executionWorkspaceApi, opportunityApi, tradeBuilderApi } from './api';
import type { OpportunityRecord, TradePlan } from './types';

const n=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export function AdvancedTradeBuilderPage(){
 const [opps,setOpps]=useState<OpportunityRecord[]>([]);const [oppId,setOppId]=useState('');const [plans,setPlans]=useState<TradePlan[]>([]);const [message,setMessage]=useState('');
 const [account,setAccount]=useState('PAPER-PRIMARY');const [capital,setCapital]=useState(100000);const [risk,setRisk]=useState(1);const [strategy,setStrategy]=useState('BULL_CALL_SPREAD');
 const [expiry,setExpiry]=useState('2026-09-18');const [longStrike,setLongStrike]=useState(100);const [shortStrike,setShortStrike]=useState(110);const [longPrice,setLongPrice]=useState(5);const [shortPrice,setShortPrice]=useState(2);
 const selected=useMemo(()=>opps.find(x=>x.opportunity_id===oppId),[opps,oppId]);
 const load=async()=>{const o=await opportunityApi.list();setOpps(o.data.filter(x=>['UNDER_REVIEW','APPROVED','TRADE_BUILT'].includes(x.workflow_state)));if(!oppId&&o.data[0])setOppId(o.data[0].opportunity_id);const p=await tradeBuilderApi.list();setPlans(p.data)};
 useEffect(()=>{load().catch(e=>setMessage(e.message))},[]);
 const build=async()=>{if(!selected)return;setMessage('');try{const right=selected.direction.includes('PUT')?'PUT':'CALL';const legs=strategy.startsWith('LONG_')?[{side:'BUY',quantity:1,option_right:right,strike:longStrike,expiry,limit_price:longPrice}]:[{side:'BUY',quantity:1,option_right:right,strike:longStrike,expiry,limit_price:longPrice},{side:'SELL',quantity:1,option_right:right,strike:shortStrike,expiry,limit_price:shortPrice}];await tradeBuilderApi.build({opportunity_id:selected.opportunity_id,expected_opportunity_version:selected.version,account_id:account,strategy,capital,risk_budget_pct:risk,legs,notes:'Created in Milestone 56 governed trade builder'});setMessage('Trade plan created and validated.');await load()}catch(e:any){setMessage(e.message)}};
 const move=async(p:TradePlan,state:string)=>{try{const moved=await tradeBuilderApi.transition(p.trade_plan_id,p.version,state,`Workstation transition to ${state}`);if(state==='PAPER_READY'){const intent=await executionWorkspaceApi.create(p.trade_plan_id,p.account_id);setMessage(`Paper execution intent ${intent.data.execution_intent_id} created.`);location.hash='#/execution-workspace';return}await load()}catch(e:any){setMessage(e.message)}};
 return <section><div className="page-title"><div><h2>Advanced Trade Builder & Execution</h2><p>Construct versioned, defined-risk option plans from canonical opportunities and normalized institutional intelligence.</p></div></div>
 {message&&<div className="handoff-message">{message}</div>}
 <div className="trade-builder-layout"><article className="panel"><h3>Construction inputs</h3><div className="scanner-form">
 <label>Opportunity<select value={oppId} onChange={e=>setOppId(e.target.value)}><option value="">Select</option>{opps.map(o=><option key={o.opportunity_id} value={o.opportunity_id}>{o.symbol} · {o.strategy} · v{o.version}</option>)}</select></label>
 <label>Paper account<input value={account} onChange={e=>setAccount(e.target.value)}/></label><label>Capital<input type="number" value={capital} onChange={e=>setCapital(n(e.target.value))}/></label><label>Risk budget %<input type="number" step="0.1" value={risk} onChange={e=>setRisk(n(e.target.value))}/></label>
 <label>Strategy<select value={strategy} onChange={e=>setStrategy(e.target.value)}><option>BULL_CALL_SPREAD</option><option>BEAR_PUT_SPREAD</option><option>LONG_CALL</option><option>LONG_PUT</option></select></label><label>Expiry<input value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>
 <label>Long strike<input type="number" value={longStrike} onChange={e=>setLongStrike(n(e.target.value))}/></label><label>Long price<input type="number" step="0.01" value={longPrice} onChange={e=>setLongPrice(n(e.target.value))}/></label><label>Short strike<input type="number" value={shortStrike} onChange={e=>setShortStrike(n(e.target.value))}/></label><label>Short price<input type="number" step="0.01" value={shortPrice} onChange={e=>setShortPrice(n(e.target.value))}/></label>
 <button className="primary" onClick={build} disabled={!selected}>Build governed plan</button></div></article>
 <article className="panel"><h3>Risk preview</h3><div className="grid metrics"><div><span>Net debit</span><b>${Math.max(0,(longPrice-shortPrice)*100).toFixed(2)}</b></div><div><span>Max loss</span><b>${Math.max(0,(longPrice-shortPrice)*100).toFixed(2)}</b></div><div><span>Risk budget</span><b>${(capital*risk/100).toFixed(2)}</b></div><div><span>Defined risk</span><b>{shortStrike!==longStrike?'YES':'REVIEW'}</b></div></div><p>Paper readiness only creates a governed execution intent. It does not enable live trading or bypass existing IBKR paper-routing controls.</p></article></div>
 <article className="panel"><h3>Trade plans</h3><div className="table-wrap"><table><thead><tr><th>Symbol</th><th>Strategy</th><th>State</th><th>Max loss</th><th>R/R</th><th>Version</th><th>Actions</th></tr></thead><tbody>{plans.map(p=><tr key={p.trade_plan_id}><td>{p.symbol}</td><td>{p.strategy}</td><td>{p.state}</td><td>${p.max_loss.toFixed(2)}</td><td>{p.reward_risk_ratio??'—'}</td><td>{p.version}</td><td>{p.state==='VALIDATED'&&<button onClick={()=>move(p,'APPROVED')}>Approve</button>}{p.state==='APPROVED'&&<button onClick={()=>move(p,'PAPER_READY')}>Prepare paper intent</button>}{p.state==='PAPER_READY'&&<button onClick={()=>executionWorkspaceApi.create(p.trade_plan_id,p.account_id).then(()=>{location.hash='#/execution-workspace'}).catch((e:any)=>setMessage(e.message))}>Open execution workspace</button>}</td></tr>)}</tbody></table></div></article></section>
}
