import type { Envelope, Health, Overview, Readiness, ScannerRun, ScannerResults, DailyScanRequest, DataRefreshRequest, ScannerUniverse, OpportunityRecord, OpportunityEvent, StageOpportunityRequest, OpportunityWorkflowState, IntelligenceBundle, TradePlan, ManagedPosition, PortfolioIntelligenceSnapshot, LearningReport, LearningPolicy } from './types';
const API_ROOT=(import.meta.env.VITE_API_ROOT||'/api/v1/platform').replace(/\/$/,'');
const SCANNER_ROOT=(import.meta.env.VITE_SCANNER_API_ROOT||'/api/v1/scanner').replace(/\/$/,'');
const INTELLIGENCE_ROOT=(import.meta.env.VITE_INTELLIGENCE_API_ROOT||'/api/v1/institutional-intelligence').replace(/\/$/,'');
const TRADE_BUILDER_ROOT=(import.meta.env.VITE_TRADE_BUILDER_API_ROOT||'/api/v1/trade-builder').replace(/\/$/,'');
const PORTFOLIO_INTELLIGENCE_ROOT=(import.meta.env.VITE_PORTFOLIO_INTELLIGENCE_API_ROOT||'/api/v1/portfolio-intelligence').replace(/\/$/,'');
const PERFORMANCE_LEARNING_ROOT=(import.meta.env.VITE_PERFORMANCE_LEARNING_API_ROOT||'/api/v1/performance-learning').replace(/\/$/,'');
const OPPORTUNITY_ROOT=(import.meta.env.VITE_OPPORTUNITY_API_ROOT||'/api/v1/opportunities').replace(/\/$/,'');
export class ApiError extends Error { constructor(public status:number,message:string,public payload?:unknown){super(message)} }
function headers(json=false){const h:Record<string,string>={'Accept':'application/json'};if(json)h['Content-Type']='application/json';const key=sessionStorage.getItem('trading-ai-api-key');if(key){h['X-API-Key']=key;h['X-Actor']='workstation-user'}return h;}
async function request<T>(url:string, init:RequestInit={}):Promise<Envelope<T>>{const r=await fetch(url,init);let body:unknown;try{body=await r.json()}catch{body={detail:r.statusText}}if(!r.ok)throw new ApiError(r.status,(body as any)?.detail||r.statusText,body);return body as Envelope<T>}
export async function apiGet<T>(path:string,signal?:AbortSignal):Promise<Envelope<T>>{return request<T>(`${API_ROOT}${path}`,{headers:headers(),signal})}
export const platformApi={health:(s?:AbortSignal)=>apiGet<Health>('/health',s),readiness:(s?:AbortSignal)=>apiGet<Readiness>('/readiness',s),overview:(s?:AbortSignal)=>apiGet<Overview>('/overview',s),portfolio:(s?:AbortSignal)=>apiGet<any>('/portfolio',s),risk:(s?:AbortSignal)=>apiGet<any>('/risk',s),execution:(s?:AbortSignal)=>apiGet<any>('/execution',s),positions:(s?:AbortSignal)=>apiGet<any>('/positions',s),exits:(s?:AbortSignal)=>apiGet<any>('/exit-instructions',s)};
export const scannerApi={
  universes:(s?:AbortSignal)=>request<ScannerUniverse[]>(`${SCANNER_ROOT}/universes`,{headers:headers(),signal:s}),
  runs:(s?:AbortSignal)=>request<ScannerRun[]>(`${SCANNER_ROOT}/runs`,{headers:headers(),signal:s}),
  run:(id:string,s?:AbortSignal)=>request<ScannerRun>(`${SCANNER_ROOT}/runs/${id}`,{headers:headers(),signal:s}),
  results:(id:string,s?:AbortSignal)=>request<ScannerResults>(`${SCANNER_ROOT}/runs/${id}/results`,{headers:headers(),signal:s}),
  refresh:(payload:DataRefreshRequest)=>request<ScannerRun>(`${SCANNER_ROOT}/data-refresh`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
  scan:(payload:DailyScanRequest)=>request<ScannerRun>(`${SCANNER_ROOT}/runs`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
};

export const opportunityApi={
  list:(state?:OpportunityWorkflowState,signal?:AbortSignal)=>request<OpportunityRecord[]>(`${OPPORTUNITY_ROOT}${state?`?state=${encodeURIComponent(state)}`:''}`,{headers:headers(),signal}),
  get:(id:string,signal?:AbortSignal)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}`,{headers:headers(),signal}),
  events:(id:string,signal?:AbortSignal)=>request<OpportunityEvent[]>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/events`,{headers:headers(),signal}),
  stage:(payload:StageOpportunityRequest)=>request<OpportunityRecord>(OPPORTUNITY_ROOT,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),
  transition:(id:string,newState:OpportunityWorkflowState,expectedVersion:number,reason:string)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({new_state:newState,expected_version:expectedVersion,reason})}),
  designatePreferred:(id:string,expectedVersion:number,reason:string)=>request<OpportunityRecord>(`${OPPORTUNITY_ROOT}/${encodeURIComponent(id)}/preferred`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,reason})}),
};

export const institutionalIntelligenceApi={get:(id:string,signal?:AbortSignal)=>request<IntelligenceBundle>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}`,{headers:headers(),signal}),generate:(id:string)=>request<IntelligenceBundle>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}/generate`,{method:'POST',headers:headers(true)}),history:(id:string,signal?:AbortSignal)=>request<any[]>(`${INTELLIGENCE_ROOT}/opportunities/${encodeURIComponent(id)}/history`,{headers:headers(),signal})};

export const tradeBuilderApi={list:(opportunityId?:string)=>request<TradePlan[]>(`${TRADE_BUILDER_ROOT}/plans${opportunityId?`?opportunity_id=${encodeURIComponent(opportunityId)}`:''}`,{headers:headers()}),build:(payload:Record<string,any>)=>request<TradePlan>(`${TRADE_BUILDER_ROOT}/plans`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),transition:(id:string,expectedVersion:number,newState:string,reason:string)=>request<TradePlan>(`${TRADE_BUILDER_ROOT}/plans/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,new_state:newState,reason})})};

export const portfolioIntelligenceApi={positions:(portfolioId='PAPER-PRIMARY')=>request<ManagedPosition[]>(`${PORTFOLIO_INTELLIGENCE_ROOT}/positions?portfolio_id=${encodeURIComponent(portfolioId)}`,{headers:headers()}),snapshot:(portfolioId:string)=>request<PortfolioIntelligenceSnapshot|null>(`${PORTFOLIO_INTELLIGENCE_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/snapshot`,{headers:headers()}),generateSnapshot:(portfolioId:string,cash:number,buyingPower:number)=>request<PortfolioIntelligenceSnapshot>(`${PORTFOLIO_INTELLIGENCE_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/snapshots`,{method:'POST',headers:headers(true),body:JSON.stringify({cash,buying_power:buyingPower})}),action:(id:string,expectedVersion:number,action:string,reason:string,realizedPnl=0)=>request<ManagedPosition>(`${PORTFOLIO_INTELLIGENCE_ROOT}/positions/${encodeURIComponent(id)}/actions`,{method:'POST',headers:headers(true),body:JSON.stringify({expected_version:expectedVersion,action,reason,realized_pnl:realizedPnl})})};

export const performanceLearningApi={report:(portfolioId:string)=>request<LearningReport|null>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/report`,{headers:headers()}),generate:(portfolioId:string)=>request<LearningReport>(`${PERFORMANCE_LEARNING_ROOT}/portfolios/${encodeURIComponent(portfolioId)}/reports`,{method:'POST',headers:headers(true)}),policies:()=>request<LearningPolicy[]>(`${PERFORMANCE_LEARNING_ROOT}/policies`,{headers:headers()}),propose:(payload:Record<string,any>)=>request<LearningPolicy>(`${PERFORMANCE_LEARNING_ROOT}/policies`,{method:'POST',headers:headers(true),body:JSON.stringify(payload)}),transition:(id:string,targetState:string,reason:string)=>request<LearningPolicy>(`${PERFORMANCE_LEARNING_ROOT}/policies/${encodeURIComponent(id)}/transitions`,{method:'POST',headers:headers(true),body:JSON.stringify({target_state:targetState,reason})})};
