from __future__ import annotations
from html import escape
from pathlib import Path

def _v(x,fmt='.2f'): return '—' if x is None else format(x,fmt)
def write_html_report(s,path:Path):
    path.parent.mkdir(parents=True,exist_ok=True)
    rows=''.join(f'<tr><td>{x.expiry}</td><td>{x.strike:.2f}</td><td>{x.net_gamma_exposure:,.0f}</td><td>{x.net_delta_exposure:,.0f}</td><td>{x.call_open_interest:,.0f}</td><td>{x.put_open_interest:,.0f}</td><td>{x.liquidity_score:.1f}</td><td>{"Yes" if x.trade_eligible else "No"}</td></tr>' for x in s.strike_exposures)
    prov=''.join(f'<tr><td>{escape(x.metric_name)}</td><td>{x.metric_class}</td><td>{x.source}</td><td>{escape(x.estimator or "—")}</td><td>{x.confidence:.2f}</td></tr>' for x in s.provenance)
    html=f'''<!doctype html><html><head><meta charset="utf-8"><title>Milestone 44 - {s.symbol}</title><style>body{{font:14px system-ui;margin:28px;color:#18212f}}.grid{{display:grid;grid-template-columns:repeat(4,minmax(180px,1fr));gap:12px}}.card{{border:1px solid #d9e0e8;border-radius:10px;padding:14px}}table{{border-collapse:collapse;width:100%;margin-top:18px}}th,td{{padding:7px;border-bottom:1px solid #e5e9ef;text-align:right}}th:first-child,td:first-child{{text-align:left}}.note{{background:#fff8db;padding:12px;border-radius:8px}}code{{background:#eef2f6;padding:2px 5px}}</style></head><body><h1>Institutional Market Structure & Dealer Positioning</h1><p>{s.symbol} · requested {s.as_of_date} · persisted option snapshot {s.option_snapshot_date} · source <code>{s.source_table}</code></p><div class="grid"><div class="card"><b>Positioning</b><br>{s.positioning_label}<br>{s.institutional_positioning_score:.1f}</div><div class="card"><b>Gamma regime</b><br>{s.gamma_regime}<br>Flip {_v(s.gamma_flip)}</div><div class="card"><b>Walls</b><br>Put {_v(s.primary_put_wall)} · Call {_v(s.primary_call_wall)}</div><div class="card"><b>Expected move</b><br>{_v(s.expected_move)} ({_v(s.expected_move_pct)}%)</div><div class="card"><b>Bull / Bear</b><br>{s.bull_probability:.1f}% / {s.bear_probability:.1f}%</div><div class="card"><b>Range / Breakout</b><br>{s.range_probability:.1f}% / {s.breakout_probability:.1f}%</div><div class="card"><b>Contracts</b><br>{s.source_contract_count:,} structure · {s.executable_contract_count:,} trade eligible</div><div class="card"><b>Confidence</b><br>{s.confidence} ({s.confidence_score:.1f})</div></div><h2>Metric provenance</h2><table><tr><th>Metric</th><th>Class</th><th>Source</th><th>Estimator</th><th>Confidence</th></tr>{prov}</table><h2>Strike and expiration profile</h2><table><tr><th>Expiry</th><th>Strike</th><th>Net GEX</th><th>Net DEX</th><th>Call OI</th><th>Put OI</th><th>Liquidity</th><th>Trade eligible</th></tr>{rows}</table><div class="note"><h2>Governance</h2><ul>{''.join(f'<li>{escape(x)}</li>' for x in s.assumptions)}</ul><h3>Warnings</h3><ul>{''.join(f'<li>{escape(x)}</li>' for x in s.warnings) or '<li>None</li>'}</ul></div></body></html>'''
    path.write_text(html,encoding='utf-8'); return path
