from __future__ import annotations
from datetime import date, datetime
from sqlalchemy import Date, DateTime, Float, Integer, String, Text, Boolean
from sqlalchemy.orm import Mapped, mapped_column
from trading_ai.database.base import Base

class SectorMembershipModel(Base):
    __tablename__='sector_membership'
    symbol:Mapped[str]=mapped_column(String(16),primary_key=True); effective_from:Mapped[date]=mapped_column(Date,primary_key=True)
    company_name:Mapped[str]=mapped_column(String(255),nullable=False); sector:Mapped[str]=mapped_column(String(96),nullable=False,index=True); industry:Mapped[str|None]=mapped_column(String(128)); sub_industry:Mapped[str|None]=mapped_column(String(128)); sector_etf:Mapped[str|None]=mapped_column(String(16)); classification_source:Mapped[str]=mapped_column(String(255),nullable=False); effective_to:Mapped[date|None]=mapped_column(Date); is_active:Mapped[bool]=mapped_column(Boolean,nullable=False,default=True); confidence:Mapped[float]=mapped_column(Float,nullable=False); last_verified_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class MarketIntelligenceSnapshotModel(Base):
    __tablename__='market_intelligence_snapshot'
    snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); universe_name:Mapped[str]=mapped_column(String(64),nullable=False); source_snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); calculation_version:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class SymbolReturnSnapshotModel(Base):
    __tablename__='symbol_return_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); symbol:Mapped[str]=mapped_column(String(16),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); return_1d:Mapped[float|None]=mapped_column(Float); return_5d:Mapped[float|None]=mapped_column(Float); return_20d:Mapped[float|None]=mapped_column(Float); realized_volatility_20d:Mapped[float|None]=mapped_column(Float); beta_60d:Mapped[float|None]=mapped_column(Float); sector:Mapped[str|None]=mapped_column(String(96)); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class CorrelationSnapshotModel(Base):
    __tablename__='correlation_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); universe_name:Mapped[str]=mapped_column(String(64),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); lookback_days:Mapped[int]=mapped_column(Integer,nullable=False); average_pairwise_correlation:Mapped[float]=mapped_column(Float,nullable=False); median_pairwise_correlation:Mapped[float]=mapped_column(Float,nullable=False); dispersion:Mapped[float]=mapped_column(Float,nullable=False); correlation_regime:Mapped[str]=mapped_column(String(32),nullable=False); sample_size:Mapped[int]=mapped_column(Integer,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class CorrelationPairSnapshotModel(Base):
    __tablename__='correlation_pair_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); symbol_a:Mapped[str]=mapped_column(String(16),primary_key=True); symbol_b:Mapped[str]=mapped_column(String(16),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); lookback_days:Mapped[int]=mapped_column(Integer,nullable=False); correlation:Mapped[float]=mapped_column(Float,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False)
class SectorBreadthSnapshotModel(Base):
    __tablename__='sector_breadth_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); sector:Mapped[str]=mapped_column(String(96),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); sector_etf:Mapped[str|None]=mapped_column(String(16)); constituent_count:Mapped[int]=mapped_column(Integer,nullable=False); breadth_score:Mapped[float]=mapped_column(Float,nullable=False); momentum_score:Mapped[float]=mapped_column(Float,nullable=False); rotation_label:Mapped[str]=mapped_column(String(24),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class MarketSentimentSnapshotModel(Base):
    __tablename__='market_sentiment_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); overall_sentiment_score:Mapped[float]=mapped_column(Float,nullable=False); risk_appetite_score:Mapped[float]=mapped_column(Float,nullable=False); fear_score:Mapped[float]=mapped_column(Float,nullable=False); sentiment_label:Mapped[str]=mapped_column(String(24),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class SentimentComponentSnapshotModel(Base):
    __tablename__='sentiment_component_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); component_name:Mapped[str]=mapped_column(String(64),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); score:Mapped[float]=mapped_column(Float,nullable=False); weight:Mapped[float]=mapped_column(Float,nullable=False); contribution:Mapped[float]=mapped_column(Float,nullable=False); direction:Mapped[str]=mapped_column(String(16),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class GenericIntelligenceSnapshotModel(Base):
    __abstract__=True
    snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); score:Mapped[float]=mapped_column(Float,nullable=False); regime:Mapped[str]=mapped_column(String(32),nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class MarketInternalSnapshotModel(GenericIntelligenceSnapshotModel): __tablename__='market_internal_snapshot'
class MarketVolatilitySnapshotModel(GenericIntelligenceSnapshotModel): __tablename__='market_volatility_snapshot'
class MarketLiquiditySnapshotModel(GenericIntelligenceSnapshotModel): __tablename__='market_liquidity_snapshot'
class MarketRiskSnapshotModel(GenericIntelligenceSnapshotModel): __tablename__='market_risk_snapshot'
class DealerPositionChangeSnapshotModel(Base):
    __tablename__='dealer_position_change_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); symbol:Mapped[str]=mapped_column(String(16),primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); positioning_score:Mapped[float]=mapped_column(Float,nullable=False); dealer_conviction_score:Mapped[float]=mapped_column(Float,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
class MarketOpportunitySnapshotModel(Base):
    __tablename__='market_opportunity_snapshot'; snapshot_timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),primary_key=True); opportunity_rank:Mapped[int]=mapped_column(Integer,primary_key=True); as_of_date:Mapped[date]=mapped_column(Date,nullable=False,index=True); opportunity_type:Mapped[str]=mapped_column(String(48),nullable=False); instrument:Mapped[str]=mapped_column(String(32),nullable=False); direction:Mapped[str]=mapped_column(String(16),nullable=False); strategy_family:Mapped[str]=mapped_column(String(48),nullable=False); score:Mapped[float]=mapped_column(Float,nullable=False); confidence:Mapped[float]=mapped_column(Float,nullable=False); provenance:Mapped[str]=mapped_column(String(32),nullable=False); payload_json:Mapped[str]=mapped_column(Text,nullable=False)
