from sqlalchemy import JSON,Float,Integer,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from trading_ai.database.base import Base
class PerformanceObservationModel(Base):
 __tablename__='performance_learning_observations'
 __table_args__=(UniqueConstraint('position_id','position_version',name='uq_m58_observation_position_version'),)
 observation_id:Mapped[str]=mapped_column(String(128),primary_key=True);position_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);position_version:Mapped[int]=mapped_column(Integer,nullable=False);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);opportunity_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True);direction:Mapped[str]=mapped_column(String(16),nullable=False,index=True);opened_at:Mapped[str]=mapped_column(String(64),nullable=False);closed_at:Mapped[str|None]=mapped_column(String(64));predicted_probability:Mapped[float]=mapped_column(Float,nullable=False);realized_return_pct:Mapped[float]=mapped_column(Float,nullable=False);outcome:Mapped[str]=mapped_column(String(16),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False);observed_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True)
class PerformanceLearningReportModel(Base):
 __tablename__='performance_learning_reports'
 report_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);window_start:Mapped[str|None]=mapped_column(String(64));window_end:Mapped[str|None]=mapped_column(String(64));generated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);analytics_version:Mapped[str]=mapped_column(String(64),nullable=False);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False);generated_by:Mapped[str]=mapped_column(String(128),nullable=False)
class LearningPolicyModel(Base):
 __tablename__='performance_learning_policies'
 policy_id:Mapped[str]=mapped_column(String(128),primary_key=True);policy_name:Mapped[str]=mapped_column(String(128),nullable=False,index=True);version:Mapped[int]=mapped_column(Integer,nullable=False);state:Mapped[str]=mapped_column(String(32),nullable=False,index=True);expected_previous_version:Mapped[int|None]=mapped_column(Integer);parameters_json:Mapped[dict]=mapped_column(JSON,nullable=False);evidence_json:Mapped[dict]=mapped_column(JSON,nullable=False);reason:Mapped[str]=mapped_column(Text,nullable=False);created_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));created_at:Mapped[str]=mapped_column(String(64),nullable=False);updated_at:Mapped[str]=mapped_column(String(64),nullable=False);activated_at:Mapped[str|None]=mapped_column(String(64));__table_args__=(UniqueConstraint('policy_name','version',name='uq_m58_policy_name_version'),)
class LearningAuditEventModel(Base):
 __tablename__='performance_learning_audit_events'
 event_id:Mapped[str]=mapped_column(String(128),primary_key=True);entity_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);event_type:Mapped[str]=mapped_column(String(64),nullable=False,index=True);actor:Mapped[str]=mapped_column(String(128),nullable=False);reason:Mapped[str]=mapped_column(Text,nullable=False);event_timestamp:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)

class TradeOutcomeModel(Base):
 __tablename__='performance_trade_outcomes'
 __table_args__=(UniqueConstraint('position_id','position_version',name='uq_m65_outcome_position_version'),)
 outcome_id:Mapped[str]=mapped_column(String(128),primary_key=True);position_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);position_version:Mapped[int]=mapped_column(Integer,nullable=False);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);opportunity_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);decision_snapshot_id:Mapped[str|None]=mapped_column(String(128),index=True);portfolio_decision_id:Mapped[str|None]=mapped_column(String(128),index=True);strategy:Mapped[str]=mapped_column(String(64),nullable=False,index=True);market_regime:Mapped[str]=mapped_column(String(64),nullable=False,index=True);outcome:Mapped[str]=mapped_column(String(16),nullable=False,index=True);predicted_probability:Mapped[float]=mapped_column(Float,nullable=False);expected_value:Mapped[float]=mapped_column(Float,nullable=False);realized_pnl:Mapped[float]=mapped_column(Float,nullable=False);realized_return_pct:Mapped[float]=mapped_column(Float,nullable=False);maximum_drawdown_pct:Mapped[float]=mapped_column(Float,nullable=False);holding_days:Mapped[float]=mapped_column(Float,nullable=False);opened_at:Mapped[str]=mapped_column(String(64),nullable=False);closed_at:Mapped[str|None]=mapped_column(String(64),index=True);reconstructed_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)

class PerformanceAttributionSnapshotModel(Base):
 __tablename__='performance_attribution_snapshots'
 attribution_snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);generated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);sample_size:Mapped[int]=mapped_column(Integer,nullable=False);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)

class ProbabilityCalibrationSnapshotModel(Base):
 __tablename__='performance_calibration_snapshots'
 calibration_snapshot_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);scope:Mapped[str]=mapped_column(String(64),nullable=False,index=True);scope_value:Mapped[str]=mapped_column(String(128),nullable=False,index=True);sample_size:Mapped[int]=mapped_column(Integer,nullable=False);brier_score:Mapped[float]=mapped_column(Float,nullable=False);log_loss:Mapped[float]=mapped_column(Float,nullable=False);expected_calibration_error:Mapped[float]=mapped_column(Float,nullable=False);generated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)

class CounterfactualOutcomeModel(Base):
 __tablename__='performance_counterfactual_outcomes'
 __table_args__=(UniqueConstraint('portfolio_id','opportunity_id','decision_state_hash',name='uq_m65_counterfactual_decision'),)
 counterfactual_id:Mapped[str]=mapped_column(String(128),primary_key=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);opportunity_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);decision_state_hash:Mapped[str]=mapped_column(String(128),nullable=False,index=True);decision:Mapped[str]=mapped_column(String(32),nullable=False,index=True);selected:Mapped[bool]=mapped_column(Integer,nullable=False);predicted_probability:Mapped[float]=mapped_column(Float,nullable=False);observed_return_pct:Mapped[float|None]=mapped_column(Float);evaluation_status:Mapped[str]=mapped_column(String(32),nullable=False,index=True);evaluated_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)

class PerformanceLearningPublicationModel(Base):
 __tablename__='performance_learning_publications'
 publication_id:Mapped[str]=mapped_column(String(128),primary_key=True);publication_name:Mapped[str]=mapped_column(String(128),nullable=False,index=True);portfolio_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);report_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);status:Mapped[str]=mapped_column(String(32),nullable=False,index=True);sample_size:Mapped[int]=mapped_column(Integer,nullable=False);published_at:Mapped[str]=mapped_column(String(64),nullable=False,index=True);payload_json:Mapped[dict]=mapped_column(JSON,nullable=False)
